### ISSUE TITLE
[FTM] Create a download_completed Firebase event

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#1000]
**User Story**
As a Product Owner,
I want to add a new custom gameplay event when Feed The Monster finishes downloading for the first time,
So that I can collect more granular information on whether we are losing people on the download of the FTM sub-app.

**Acceptance Criteria**
Given that I have implemented the new data collection event,
When I trigger those events and look at the collected input in BigQuery,
Then I should be able to verify that the events are collecting the type of data we are looking for.

**Comment by ashishkrr** [comment]
Hey @burrage, I have a doubt. Where are we going to implement this event? Is it on the FTM side or Curious Reader? I'm just confirming because in the sprint, we were discussing that soon we may remove FTM Firebase and only use Curious Reader Firebase.

**Comment by burrage** [comment]
@ashishkrr That's a great question!

If we went the Curious Reader route, would we report the event when we receive the boolean value notification in the Curious Reader app from the FTM web app that the service worker has everything it needs to play? 

Does that communication between the FTM JS app and the container app happen immediately after the service worker finishes downloading?

Would there be any concerns if we went the route of reporting this within Curious Reader?

And to reiterate, the purpose of collecting this "download_compelted" event is solely on whether the event happens or not so we could technically troubleshoot what might be preventing someone from even getting into playing FTM (and subsequently pressing the "play" button-- because at least with that event, we know the person is making a conscious decision to press it or not!).

**Comment by Rajesh1041** [comment]
@burrage we have an issue #948 where even after downloading it, we are unable to play. In that case if we log the data [download_completed] then user is not able to play it, so there might be some problem related to download happened. We can hold this task until we find the reason why its happening, to get a clear understanding.

**Comment by burrage** [comment]
@Rajesh1041 Can we replicate #948 for FTM too? Or is it just the interactive books?

**Comment by Rajesh1041** [comment]
@burrage We didn't face this issue in FTM Ben!

**Comment by burrage** [comment]
And I've removed the #948 blocker as it doesn't seem like it would affect FTMJS.
