### ISSUE TITLE
Play positive feedback sound as the written feedback text appears

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#1020]
**User Story**
As a UX designer,
I want to play this [positive feedback sound](https://github.com/curiouslearning/FeedTheMonster/blob/master/Feed%20the%20Monster/Assets/Sounds/Game/PointsAdd.wav) when the animation for the written feedback text to display plays,
So that we are giving enough positive feedback and encouragement through SFX to keep engagement in the task going.

[Video reference from FTM Unity-- it's played when the graphical shine goes from right to left which is after the feedback phrase "Superb!" is spoken](https://drive.google.com/file/d/1aGQsK6gcj6gWPe69SNWLNGJkECXYl-hy/view?usp=sharing)

**Acceptance Criteria**
Given that we have answered a question correctly,
When the written feedback text begins to appear,
Then I should hear this [sound effect](https://github.com/curiouslearning/FeedTheMonster/blob/master/Feed%20the%20Monster/Assets/Sounds/Game/PointsAdd.wav) and the spoken language audio of that feedback.

**Comment by Ashish1998** [comment]
@burrage Hiii Ben, Here actually the positive feedback sound is added but it plays after the Feedback text animation (can be observed in the below video which i have attached), so we had a doubt that should it play when the text animation starts? . Please give your valuable feedback on this.
Thank you.

https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/02896d71-a59f-45e7-9f53-ad4222c0f709

**Comment by burrage** [comment]
@Ashish1998 Could I see it playing when the text animation starts please? I want to make sure the experience feels like it isn't taking a long time between questions and that might shorten the time (?) while still giving the right amount of sound feedback (it's feeling better!)

Thanks!
