### ISSUE TITLE
Play disappointed monster SFX randomly after "eat" SFX and before "spit" SFX when getting a question wrong

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#1022]
**User Story**
As a UX designer,
I want to randomly decide whether or not to play this [disappointed monster SFX](https://github.com/curiouslearning/FeedTheMonster/blob/master/Feed%20the%20Monster/Assets/Sounds/Monsters/Disapointed-05.mp3) after the "eat" SFX but before the "spit" SFX when someone gets the answer wrong,
So that sometimes we provide a little extra audio clue that the monster doesn't like when you feed it a letter it doesn't want.

**Acceptance Criteria**
Given that I am playing FTM,
When I drag an incorrect stone,
Then I should randomly decide whether or not to play the [disappointed monster SFX](https://github.com/curiouslearning/FeedTheMonster/blob/master/Feed%20the%20Monster/Assets/Sounds/Monsters/Disapointed-05.mp3) and if we chose to play it then I should hear it and if we chose not to we shouldn't hear the disappointed monster SFX.

**Comment by Nikhil77sutara** [comment]
Hey @burrage ,
I hope you are doing well,
I've implemented the requested changes in the audio sequence for when an incorrect stone is selected. Now, we're incorporating the disappointed audio between the "eat" SFX and "MonsterSpit" SFX, as per the task requirements. Previously, only the "MonsterSpit" audio played in this scenario, but now we've added the extra audio indicator. I've attached a video for your review. Please take a look and confirm if everything aligns with the task specifications.

Uploading Feed The Monster - Google Chrome 2024-03-27 21-07-44.mp4…

**Comment by burrage** [comment]
Hey @Nikhil77sutara! The only other thing to verify for the acceptance criteria is that sometimes the "uh-oh!" audio _doesn't_ play when getting the answer wrong. Otherwise, this works to spec for this particular task.

We'll have to spin up another task card to improve the spitting animation and better align the "spit" SFX to that animation because there's a bit of UX dissonance that these two SFX don't match up to the animation on the screen (e.g. the "Uh-oh!" is happening while the monster is already animating the stone flying out!). 

One question while we're in this particular piece of code that would be helpful to understand the scope of that future task a little more... The Unity version pauses while the character goes, "Uh oh!" and _then_ the "spit" SFX plays simultaneously as the animation occurs. Is the code architected in such a way that this is possible to do at the same time as updating the spit animation? Or is the animation happening the current cueing mechanism for playing "Uh oh!" and then the "spit" SFX?

Thanks Nikhil!

**Comment by Nikhil77sutara** [comment]
Thank you @burrage for addressing these matters. Currently, we are indeed playing all three SFX in a sequence, similar to how we handle correct stones, ensuring consistency in our audio feedback system. Regarding the "uh-oh" audio, I took the liberty of testing it in various levels and  found that it is playing correctly.
