### ISSUE TITLE
Add positive feedback sound to play at the same time as eating sound when getting correct answer

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#1025]
**User Story**
As a UX designer,
I want to play this [positive SFX](https://github.com/curiouslearning/FeedTheMonster/blob/master/Feed%20the%20Monster/Assets/Sounds/Game/CorrectStoneFinal.mp3) at the same time as the eating sound when I get a correct answer,
So that we are adding positive sound effects that help to increase engagement.

Note: I can't find the actual sound from FTM Unity that plays so I have substituted it with another SFX I found while browsing.

**Acceptance Criteria**
Given that I am playing FTM JS,
When I drag the correct stone to the monster,
Then I hear this new [positive SFX](https://github.com/curiouslearning/FeedTheMonster/blob/master/Feed%20the%20Monster/Assets/Sounds/Game/CorrectStoneFinal.mp3) and the eating SFX at the same time before the spoken feedback audio.

**Comment by Nikhil77sutara** [comment]
Hi @burrage,
I trust you're doing well. I'm seeking clarification regarding the word puzzle feature. With multiple stones for a single word, should the [positive SFX ](https://github.com/curiouslearning/FeedTheMonster/blob/master/Feed%20the%20Monster/Assets/Sounds/Game/CorrectStoneFinal.mp3) play after placing all correct stones, as we're triggering feedback audio when all stones are correct? Or should it play after each successful stone drop? Clarifying this will help ensure we maintain a cohesive user experience.

Best regards,
Nikhil

**Comment by burrage** [comment]
10 out of 10 question @Nikhil77sutara !

Looking back at the Unity version, on word spelling levels, a very slightly different sound effect plays after each correct stone followed by the SFX we linked on the very _last_ stone. 

Since it is such a subtle difference in sound that might not make a huge difference, let's go ahead and try this same sound effect linked in the task card for each correct stone and see how it sounds and we can decide from there.

**Comment by Nikhil77sutara** [comment]
> 10 out of 10 question @Nikhil77sutara !
> 
> Looking back at the Unity version, on word spelling levels, a very slightly different sound effect plays after each correct stone followed by the SFX we linked on the very _last_ stone.
> 
> Since it is such a subtle difference in sound that might not make a huge difference, let's go ahead and try this same sound effect linked in the task card for each correct stone and see how it sounds and we can decide from there.

Sure ,
Thanks Ben!
