### ISSUE TITLE
Find a tech tool that would allow us to keep track of features and functionality that are in each version of FTM JS

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#1063]
**User Story**
As a Tech Lead and Product Owner,
I want to find a tool that helps us document the changes that go into each production Feed The Monster release,
So that we can see what changes went into each release and how these changes may affect the engagement and retention of users as we experiment over time.

**Acceptance Criteria**
Given that we want to know what features and functionality made it into each production release of Feed The Monster,
When asked about what tool we should use and the process we'd need to follow to use the tool,
Then I should be able to make a tool recommendation and help describe the resources and process needed to make the tool display the changes that go into each version of FTM.

**Comment by amitsinghsutara** [comment]
Hey @burrage ,

Hope you are doing well,

Regarding creating a process for listing and documenting the changes that go into each production Feed The Monster release,
We have tried to implement the github release notes using tags in this [repo](https://github.com/amitsinghsutara/github-release-note-repo),
Here you will see a new tag i.e. [Releases]([Releases 6](https://github.com/amitsinghsutara/github-release-note-repo/releases)) , where we can some release version's on this repo only which have some notes as well like the pr which were merged,
Also Ben we can attach our taskcard number as well for more info!

**Comment by burrage** [comment]
Love all of this, Amit! This is precisely what we were looking for and a great conversation to be had at Sprint Review with everyone!

One question about this approach-- in the future, would it be possible to post the Changelog automatically somewhere, like in Slack? We don't have to do it now; we just need to have an idea of how to do it.

And to ensure I understand the process thoroughly and have it documented as a strawman to be discussed with the group (this can be transferred to a Google Doc for safekeeping and modified over time to remove ambiguity) before we implement this new process...

-------

In Github, someone (we should discuss who this would be) is creating a Release that we want to name in our Major.Minor.Patch standard format (e.g. 1.0.29, etc. etc.). 

Someone (we should discuss who this would be) ensures each task is tagged to a Release version.

The Changelog becomes the rollup of all the commits. To make sure the Changelog is easily understandable by both a technical and non-technical audience we should make sure that the commit sentence ... (let's discuss this!)

If a task ISN'T finished in time to be part of the release, someone (we should also discuss who this would be) must move it over to the next release.

-------

And some more follow-up questions you may have seen me hinting at with my questions in the channel about whether we can only prompt users to update on a Major or Minor... If we move to a more frequent release schedule than once per sprint... How would that change our proposed Release / Release Notes process? Would the process remain the same?

Anywho... Great job on this so far to queue up the conversation with everyone!

**Comment by burrage** [comment]
^^ CC @jeffoberlander as FYI to help in discussion at Sprint Review

**Comment by burrage** [comment]
@amitsinghsutara Heads up that I'm going to edit this right now to be a little more clear and break it up into two separate cards-- this one (finding a tool that would allow Release Notes) and a second task, the process.

**Comment by burrage** [comment]
OK I've gone ahead and untangled that by editing the User Story and Acceptance Criteria above for this task and I've spun off the second task which will be working with Jeff.

And also to be clear you don't necessarily have to be part of that new task if you don't want to @amitsinghsutara :-)

I hope this makes this task's end state a little less ambiguous-- we've identified a tool and process for how we would use said tool and it'll be folded into a larger "release / versioning" process conversation.

**Comment by amitsinghsutara** [comment]
Hey @burrage ,

Re:- One question about this approach-- in the future, would it be possible to post the Changelog automatically somewhere, like in Slack? We don't have to do it now; we just need to have an idea of how to do it.

Yes Ben we can automatically send the changelog through slack!
