### ISSUE TITLE
QA Automation of events: level_completed

### ISSUE THREAD

**Issue by divyahariharan2103** [curiouslearning/FeedTheMonsterJS#1077]
**User Story**
As a developer,
I want to make sure that the level_completed event is being reported and stored into BigQuery daily, that the values collected for the event are what we would expect them to be, and that we are alerted of issues if the event is NOT being collected or we are collecting values of data that are not expected,
So that we can make sure this critical event is being logged and logged correctly as part of normal operation of the application.

**Acceptance Criteria**
Given that I have written my QA script,
When the QA script runs daily,
Then I should be informed whether or not the conditions of the QA tests pass or fail.

**Additional Info**
Make sure the event puzzle_completed has the following keys and values as expected:

**KEY_NAME**
success_or_failure
number_of successful_puzzles
level_number
profile_number
cr_user_id
ftm_language
version_number
json_version_number
duration

**EXPECTED VALUE TYPE**
string
int
int
int
string
string
string
double
double

**RECEIVED VALUE TYPE**
string
int
int
int
string
string
string
double
double

**Comment by Nikhil77sutara** [comment]
Hy @burrage ,
Hope you are doing well.
 `if the event is NOT being collected ` 
 I just want to confirm for the events if its not logged as mentioned in the task card. For example, If we have trigerred 10 events and out of 10 only 9 events are logged than how we will check which event is skipped.Can you please clarrify this thing!
 Thanks Ben.

**Comment by burrage** [comment]
So that portion is talking about a basic pass / fail condition of does that event type get reported _at all_ on any given day. 

If there are no level_completed events for any given day... that's a problem! The only time that could trigger because of a non-technical-related problem would be if indeed, nobody completes a level, but the odds of that happening are just about 0 given the volume of users we have.

Does that make sense?

**Comment by burrage** [comment]
So for a query, you'd just be checking that

WHERE event_name = 'level_completed'

returns at least 1 result.
