### ISSUE TITLE
Connect GitHub Release feature to public Slack channel

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#1112]
**User Story**
As a Tech Lead and Product Owner,
I want to automatically post the Release Notes from the Release feature in GitHub to the public #release_notes channel,
So that we can test logging our work completed over time transparently to technical and non-technical stakeholders that frontloads the level of effort.

**Acceptance Criteria**
Given that we have made commits to development,
When we make a push to production,
Then the Release Notes should be pushed automatically to the #release_notes Slack channel.

**Comment by amitsinghsutara** [comment]
Hey @burrage ,
hope you are  doing well ;)
Ben I have created a another  dummy [repo](https://github.com/amitsinghsutara/New-Testing),
here I have tried using "release-it" npm module using which we can define our own lables like this:- 
![image](https://github.com/curiouslearning/FeedTheMonsterJS/assets/102941445/5760204d-a355-4275-80a2-102fc681d6ef)

Also Ben For documenting the release notes we are creating  a [CHANGELOG.md](https://github.com/amitsinghsutara/New-Testing/blob/main/CHANGELOG.md) file  using "release-it" node package automatically where can categories our commits based on features and bug fixes like this:-
![image](https://github.com/curiouslearning/FeedTheMonsterJS/assets/102941445/25fe0cb0-5ae4-4de5-a292-60d6060a2bcd)

Using this node package we can automatically create release notes and categories them,
As per automatically posting the release notes in public slack channel Ben I am still working on it, Currently trying to send the updated CHANGELOD.MD file to the slack channel using github actions workflow!

**Comment by burrage** [comment]
What a good find! Thanks for the update @amitsinghsutara !

Cool cool on GitHub Actions-- keep me posted!

**Comment by amitsinghsutara** [comment]
Also Ben,
There's one concern as well,
Currently we are using node module "release-it" which we are running from the command interface I.e. using "run npm release" but for sending message to slack we are utilising the workflow which sends release notes automatically by extracting them from change log.md file,

So the teams concern is do we want to automatically create release as  well using the workflow besides using the command line interface!

**Comment by amitsinghsutara** [comment]
Hey @burrage ,

Hope you are doing well ;)

Status update:- 
We are automatically able to run release-it module as well!

**Comment by burrage** [comment]
Hey @amitsinghsutara!

That's good news!

I think I might not fully understand the order of steps in this proposed process with this new tool in the mix, so I'm having a bit of trouble understanding the team's concern about "automatically creating a release."

I'll go ahead and lay out my understanding of the proposed process as it stands (please correct me where I'm wrong!):

1.) Developer Lead reviews development PR and merges to main.
2.) Developer Lead runs release-it manually to build CHANGELOG.md and create a new release (is this second part right? Or is release-it ONLY building the CHANGELOG.md file?)
3.) (not sure on this part) There's some process that is looking for changes (is this a Google Cloud Function or ...?) to the CHANGELOG.md file.
4.) When the CHANGELOG.md file is changed, the process looking for changes will automatically post the CHANGELOG.md file as-is to the #release_notes Slack channel.

Is this correct? If not, let's write out these steps :-)

**Comment by amitsinghsutara** [comment]
So here's the thing Ben,
Once pr get's merged into main brach our  GitHub Actions workflow automates the process of sending release notes to a Slack channel whenever changes are pushed to the main branch. Here's what it does:

Set up Git: Configures Git with your email and username for committing changes during the workflow.
Checkout Code: Fetches the latest code from the repository.
Install Dependencies: Installs any necessary dependencies using npm.
Run release-it: Executes the release-it command to create a new release. This  updates the CHANGELOG.md file with release notes.
Extract Release Notes: Extracts the release notes from the CHANGELOG.md file using the ffurrer2/extract-release-notes action.
Extract Version Number: Parses the version number from the CHANGELOG.md file.
Commit Changes (Optional): Commits the changes made to the CHANGELOG.md file during the release process. This ensures that any modifications are included in the subsequent push to GitHub.
Send to Slack: Sends a message to a Slack channel containing the newly extracted release notes and version number.
