### ISSUE TITLE
Investigate: Sentry technical issues that could affect a user's completion of level 1

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#1114]
**User Story**
As a developer and Product Owner,
I want to view the Sentry reports to see if there are any large spikes of issues that might be causing interference with progression to completing the first level and document them as task cards,
So that we begin investigating other avenues besides just UX that might be impacting engagement.

**Acceptance Criteria**
Given that I have access to Sentry,
When I view the reports,
Then I should note any trends of things we might want to investigate technically and document them as a new task card for a future sprint.

**Comment by rakshith-arch** [comment]
Hi @burrage, when i try to login Sentry to check reports, it says that membership has to be upgraded
![image](https://github.com/curiouslearning/FeedTheMonsterJS/assets/62013445/3c869b0f-9065-45fa-89be-92def69479fc)

**Comment by burrage** [comment]
Thanks for letting me know @rakshith-arch . See Slack channel for further details!

**Comment by rakshith-arch** [comment]
Sure @burrage thank you!

**Comment by rakshith-arch** [comment]
Hi @burrage @jeffoberlander , i have shared a [report](https://docs.google.com/document/d/1LM9weOvo7yGdmKeEzmhUH4h1yFjFn3pqay3NxdlLREg/edit), for issues in the sentry.

**Comment by burrage** [comment]
@rakshith-arch What's the timeframe of this report?

If the only issue that's sticking out is only affecting 6 users out of the 92,000+ active users we have that's phenomenal.

**Comment by divyahariharan2103** [comment]
Moving it to Done as per internal discussion during sprint planning
