### ISSUE TITLE
CR/FTM transition plan / knowledge transfer to teammates

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#1115]
Please identify any parts of the code you may have specialized in (e.g. attribution and the install referrer especially) and let's plan over the next few weeks to make sure a teammate(s) can pick up where we have left off.

**Comment by divyahariharan2103** [comment]
Hi @burrage , Please find the topics that will be covered in the KT sessions that we have scheduled for the couple of days:

**19-04-2024**

- [ ] Home screen UI
- [ ] Deeplinking
- [ ] Install referrer

**22-04-2024**

- [ ] Monster component 
- [ ] Gameplay screen 
- [ ] Audio component 
- [ ] Caching PWA


**23-4-2024**

- [ ] Feedback text animation
- [ ] Ripple animation
- [ ] Firebase event integration

**24-04-2024**

- [ ] Implemented fetching manifest json data 
- [ ] Implement caching of manifest json data 
- [ ] Dropdown popup

**Comment by ashishkrr** [comment]
@divyahariharan2103 @Rajesh1041 @burrage 
Here is the Doc link
https://docs.google.com/document/d/1uDrhM9oY4QaNdu4Pf8WG42zn_6UmrjJskXfA-G1KBvg/edit
