### ISSUE TITLE
French build Issues.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#146]
- **In the French build in some levels the options are not proper**.
 
![Screenshot_2023-01-19-11-56-04-559_com example ftm](https://user-images.githubusercontent.com/99384703/213371914-5b7a3bb6-2a26-4034-aa7e-43637fc1c28e.jpg)

- **In some levels same options are present. (same letter is present twice)**

 ![Screenshot_2022-11-09-12-01-22-614_com.example.webapps.jpg](https://images.zenhubusercontent.com/623b0e5da1bf54266c59b5e8/22a2d6ed-576f-4eec-ba91-bf60f802c65e)

- **In some levels only single option is present.**
 
![Screenshot_2022-11-09-12-02-14-844_com example webapps](https://user-images.githubusercontent.com/99384703/213371817-38548a51-be47-481b-bef7-2eb2719eb56c.jpg)

**Comment by burrage** [comment]
Closing as we will make a new version with a regenerated JSON file that should solve all these issues.
