### ISSUE TITLE
Some of the prompt audios are not playing in English build.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#201]
**Description**
In some of the levels the prompt audios are not playing even in online mode in the English build of container app, in the log it shows 404 error .
The list of levels with the issue is mentioned below,

<img width="176" alt="Capture2 " src="https://user-images.githubusercontent.com/99384703/215989324-353f98e7-05dc-42bb-85e1-edd336579eb5.PNG">

The links with error are mentioned below.

https://curiousreader.org/wp-content/uploads/USENGLISH_sounds_words_lit.wav
https://curiousreader.org/wp-content/uploads/USENGLISH_sounds_words_nit.wav
https://curiousreader.org/wp-content/uploads/USENGLISH_sounds_letters_ad.wav
https://curiousreader.org/wp-content/uploads/USENGLISH_sounds_letters_it.wav
https://curiousreader.org/wp-content/uploads/USENGLISH_sounds_words_pride.wav
https://curiousreader.org/wp-content/uploads/USENGLISH_sounds_letters_og.wav
https://curiousreader.org/wp-content/uploads/USENGLISH_sounds_words_bit.wav
https://curiousreader.org/wp-content/uploads/USENGLISH_sounds_letters_eap.wav

**Comment by burrage** [comment]
I'm not actually seeing that we recorded these words (or letters!) so I have to check back with our content manager.

**Comment by burrage** [comment]
@divyahariharan2103 @Ashish1998 These missing audio prompts have been recorded and were uploaded to the curiousreader.org server.

Would you all like a Google Drive link or is the upload to the curiousreader.org server sufficient?

**Comment by divyahariharan2103** [comment]
@burrage Thanks Ben !!
we are able to access it from the server
