### ISSUE TITLE
Screenshot of curios reader container app [Main page] 

### ISSUE THREAD

**Issue by divyahariharan2103** [curiouslearning/FeedTheMonsterJS#222]

**Comment by Ashish1998** [comment]
Hiii @burrage I have attached the screenshot of container app main page.
Thank you.

![Screenshot_2023-02-14-12-50-10-565_org curiouslearning container](https://user-images.githubusercontent.com/99384703/218673216-b2181991-e36c-4bbd-8731-c47a6e38ba61.jpg)
