### ISSUE TITLE
Circle CI set up for deployment to Production AND Development AWS S3 buckets

### ISSUE THREAD

**Issue by divyahariharan2103** [curiouslearning/FeedTheMonsterJS#232]
**User Story**
As a developer,
I want to set up Circle CI to deploy the Feed The Monster project to a Production S3 bucket when we push code to main,
So that production storage is updated automatically when new code is pushed to the production branch (main).

As a developer,
I want to set up Circle CI to deploy the Feed The Monster project to a Development S3 bucket when we push code to a development branch,
So that development storage is updated automatically when new code is pushed to the development branch.

**Acceptance Criteria**
Given I have made a change to the Feed The Monster code,
When I push that change to the production branch (main),
Then the files on the Production S3 bucket should be updated accordingly.

Given I have made a change to the Feed The Monster code,
When I push that change to the development branch,
Then the files on the Development S3 bucket should be updated accordingly.

**Comment by burrage** [comment]
@divyahariharan2103 Just a heads up that I detailed out this story and spun off a related issue, #258, that will need someone on the team to perform the Acceptance Criteria checks (especially the one around making sure the Curious Reader container app is pulling from the correct URL).

**Comment by divyahariharan2103** [comment]
Sure @burrage Once the issue is done please let me know I will have anyone from the team to look into it.

**Comment by dz4va** [comment]
@burrage @divyahariharan2103 Both production and development URLs are up and ready to be used:
- Dev: https://feedthemonsterdev.curiouscontent.org/ 
- Prod: https://feedthemonster.curiouscontent.org/
