### ISSUE TITLE
Run ads for the Curious Reader app

### ISSUE THREAD

**Issue by divyahariharan2103** [curiouslearning/FeedTheMonsterJS#233]

**Comment by burrage** [comment]
We ran into an issue where Facebook was not receiving information from the app. We had forgotten to turn on the auto-collection of events and to turn off Advertisement ID collection.

Data is flowing to Facebook now so we will run ads again in the following sprint.

**Comment by burrage** [comment]
Data flowed only to the developer console and not to the Ad Console, so we are back to troubleshooting.

**Comment by burrage** [comment]
Needed to update the Facebook SDK. Installs are logging in the Ad Console now!
