### ISSUE TITLE
App title change + AAB export for Play Store Upload 

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#238]
![Screenshot_2023-02-23-10-28-01-422_com.miui.home.jpg](https://images.zenhubusercontent.com/58c973a851aa2c3057788ef8/3147a317-7403-412c-b333-c4ab3eb797d0)

We'll need to change the app name from "FTM" shown here to "Curious Reader".

We'll also need the app exported in .aab format so we can upload it to the Google Play Store.

**Comment by ashishkrr** [comment]
@burrage Just wanted to confirm do you need production build .abb export file or debug mode build .abb file.
Is this required now at current state of development or it require after fixing all issue and bugs?

**Comment by burrage** [comment]
@ashishkrr Production build and save it for the end of the sprint for sure. 

We have dependencies here like needing FTM deployed to the production URL and what that URL will be.

**Comment by burrage** [comment]
And yes, also to get as many bug fixes in as possible :-)
