### ISSUE TITLE
Create Bug Report issue template in Zenhub

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#242]
It would be super helpful to create a Bug Report issue template in Zenhub that anyone can report issues with enough details to be useful in troubleshooting for the Feed the Monster project.

**Comment by divyahariharan2103** [comment]
@burrage Can you please elaborate on this.
@Ashish1998 already follows a standard to create the bug and adds details

**Comment by burrage** [comment]
Sure. Through Github, you can create an "issue template".

This means that ANYONE (not just @Ashish1998 !) can click to create a new issue, select the template, and it will pre-populate with the information that would be needed to troubleshoot the problem.

This will create a standard for how information is relayed and reduce the amount of back-and-forth communication time needed to replicate an issue.

**Comment by divyahariharan2103** [comment]
HI @burrage I was looking into this and seems like we need to have the Admin permission to create a template for the repo
Attaching the steps: https://help.zenhub.com/support/solutions/articles/43000074624-create-multiple-new-issue-templates-in-a-workspace

I was unable to get this option

**Comment by burrage** [comment]
Ah indeed. Are you going to take on this task @divyahariharan2103 ? If so, you should be good to go now. If someone else is going to be assigned, let me know who and I'll up them to Admin.

**Comment by divyahariharan2103** [comment]
Thanks Ben !!
I have created the template![SnapCrab_NoName_2023-3-9_12-0-8_No-00.png](https://images.zenhubusercontent.com/63d75b4c03fbfb55de1ee550/4230546f-d32d-4ad3-afce-e1d1fb4d6d45)
