### ISSUE TITLE
Serve Production and Development S3 bucket content via Cloud Front

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#258]
**User Story**
As a developer,
I want to serve the Production and Development S3 bucket content via Cloud Front,
So that the content is served over HTTPS and anyone can visit the production and development URLs and immediately see and test new changes that might be made to the Feed The Monster code.

**Acceptance Criteria**
Given that I have the Production URL beginning with https:// ,
When I visit the Production URL via smartphone,
Then the Feed The Monster game should download the content from the Production S3 bucket and be playable.

Given that I have the Curious Reader container app,
When I choose to install the Feed the Monster (English),
Then the Feed The Monster game should be loading via HTTPS served from Cloud Front and the Production S3 bucket. 

Given that I have the Development URL beginning with https:// ,
When I visit the Development URL via smartphone,
Then the Feed The Monster game should download the content from the Development S3 bucket and be playable.

**Comment by burrage** [comment]
@dz4va When Cloud Front set up is finished and serving the S3 bucket content over HTTPs, can you please provide the Production and Development URLs in this thread so that others on the team can be aware and update the Curious Reader container app accordingly? Thanks!

**Comment by dz4va** [comment]
@burrage @divyahariharan2103 Both production and development URLs are up and ready to be used:
- Dev: https://feedthemonsterdev.curiouscontent.org/ 
- Prod: https://feedthemonster.curiouscontent.org/
