### ISSUE TITLE
Move app URLs into the CR container app manifest file

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#307]
**User Story**
As a Product Owner,
I want to be able to change the manifest file, on both the prod and dev Curious Reader container app, to insert everything needed to launch a new app in the Curious Reader container app,
So that we do not need to go through the Google Play review process when we want to release a new piece of content within the Curious Reader container app.

**Acceptance Criteria**
Given that I have a DEV manifest file with only one app (FTM JS),
When I add a second entry (Let's Fly) to the DEV manifest and launch the DEV Curious Reader container app,
Then I should see the Let's Fly app icon, title, and should be able to download, cache, and launch that app from that app's DEV URL.

**Comment by ashishkrr** [comment]
@burrage can you please provide more information here. So currently the meta-data manifest.json file are locally kept and that is being used to render web apps in CR container.

As per this story, am assuming we are going to host that manifest.json file in some server, and from CR container we will fetch and cache all meta-data content from file and render that, and in future we will update that manifest.json file in server so we don't need to upload new APK in google play console and go under review process. is this correct ? if not please explain me for clarity.

**Comment by divyahariharan2103** [comment]
@burrage Hi Ben ,
Can you please provide requested information to Ashish whenever possible as this is High priority issue

**Comment by burrage** [comment]
@ashishkrr That's correct.

**Comment by burrage** [comment]
Would there be any issue in using one of our *.curiouscontent.org buckets for storing the manifest?

For testing purposes, it can really be anywhere-- e.g. feedthemonsterdev.curiouscontent.org/manifests/curiousreaderdev-manifest.json.

**Comment by ashishkrr** [comment]
@burrage No ben there won't be any issue for curiouscontent.org buckets for storing the manifest.
