### ISSUE TITLE
After the timer ends it is not moving to the next level.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#330]
**Describe the bug**
After the timer ends it is not taking the user to next level, it waits for the input from user then after giving in even after timer has ended it goes to next level.

**To Reproduce**
1. Download and install the latest version of  Curious reader container app. (version v1.0.9) 
2. Open the app and click on FTM icon and download the content.
3. Click on play button and go to the first level.
4. Don't give any input wait for the timer to end.

**Expected behavior**
When the timer ends it should take the user to next level.

**Screen Record**

https://drive.google.com/file/d/1nFhggv2PMnhLQuMY7KLRPR3JMKTyvpIF/view?usp=share_link

**Smartphone (please complete the following information):**
 - Device: MI Note 6 Pro
 - OS: Android 9

**Additional context**

**Comment by burrage** [comment]
This will be hard to troubleshoot as it is only happening on one device consistently and not happening on other devices at all. It sounds like a race condition, but the weird thing is it happens CONSISTENTLY on the device this error was logged so maybe it isn't a race condition?

Might we add some code that could catch IF it is happening (using Ashish M's device to see if it is catching the error properly) and shoot this specific type of alert to Sentry so we might be able to discover the volume of this happening and maybe find commonalities between device/browser types that this happens on...???

**Comment by burrage** [comment]
@Ashish1998 It's been a while and I think we might be able to close this one. Does this happen in v1.0.19 still? If not, we can close it :-)

**Comment by Ashish1998** [comment]
@burrage This issue is not happening in the latest version v1.0.19.

**Comment by burrage** [comment]
I love these issues that solve themselves over time! Thanks @Ashish1998!
