### ISSUE TITLE
Technical exploration into multi-part FTM experience

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#342]
**User Story**
As a UX designer,
I want to see if there would be any technical issues or technical ramifications (positive or negative) if we were to split up Feed The Monster into 6 parts, with each part containing a new monster egg to evolve throughout playing that particular part,
So that we can understand what the advantages and disadvantages would be to splitting Feed The Monster like this would be and what technically would be required to achieve this splitting (e.g. separate JSON files, etc.)

**Acceptance Criteria**
Given that I am given a Google Doc link to a report containing a simple PRO and CON list,
When the Product Owner, UX designer, and Pedagogy Expert meet,
Then they should be able to understand the strengths and weaknesses to this splitting approach from a technical end that can be discussed.

**Comment by rakshith-arch** [comment]
Hi @burrage can we know the intention behind splitting json, is it to save memory or to have a good user experience?

**Comment by rakshith-arch** [comment]
Hi @burrage we have mentioned the pros and cons in the below documentation
(https://docs.google.com/document/d/1DWzILI7S818ttjZ5rbdPpNpxrMUoOXSbnk8YBxfwbnc/edit#)
