### ISSUE TITLE
Report FTM content JSON version # in all Firebase events

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#349]
**User Story**
As a data analyst,
I want to add a json_version_number to all custom FTM Firebase events (session_start, session_end, level_completed, and puzzle_completed) that uses the "majversion" and "minversion" fields from the generated JSON in a {majversion}.{minversion} format (ex. 1.1, 5.3, etc.). 

[Full spec](https://docs.google.com/document/d/1HJ8GG5w6gDqHrgs7YW0FRHhQAMYPVVrG7M81vokcjVY/edit?usp=sharing)

**Acceptance Criteria**
Given that I have played FTM web and generated session_start, session_end, puzzle_completed, and level_completed events,
When I view the events in BigQuery,
Then I should see a json_version_number attached to each event that corresponds to the major and minor versions listed in the JSON file used to power the language the events were generated for.

**Comment by divyahariharan2103** [comment]
HI @burrage , for the languages already in production we need to regen the JSONS for updating this. Please suggest what needs to be done

Thanks,
Divya
