### ISSUE TITLE
If we download Hindi content then English version icon changes to color icon. 

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#355]
**Describe the bug**
If we download the Hindi content in FTM Hindi version then, English FTM version icon changes to color icon from grey icon.

**To Reproduce**
1. Install the CR Container app from latest build which consists Hindi FTM.
2. Open the app and click on FTM Hindi version and download the content.
3. Then come back to CR app, and we can observe the English FTM icon is getting changed but not Hindi version.

**Expected behavior**
If we download the content of a particular language then, the respective icon should change.

**Screen Record**

https://images.zenhubusercontent.com/518897719/7412ede7-46df-4cec-82e4-7ebc7424193f/screenrecorder_2023_04_17_11_58_54_693.mp4

**Smartphone (please complete the following information):**
 - Device: MI Note 6 pro
 - OS: Android 9

**Additional context**

**Comment by burrage** [comment]
This one is interesting...

Before we fix this one, I'd like to see if the problem persists after implementing the language toggle in the April 21st sprint which would change which apps are available and only show one Feed The Monster language at any given time.

**Comment by Ashish1998** [comment]
Yeah @burrage we can check that case and see if this issue arises there.

**Comment by divyahariharan2103** [comment]
Not reproducible hence closed the issue
