### ISSUE TITLE
Pass & parse language information from ad to a CR container install

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#363]
**User Story**
As a user,
I want the Curious Reader container app to auto-select a language for me based on information passed to the app upon install,
So that I can immediately start seeing relevant content without having to select a language.

**Acceptance Criteria**
Given that I have seen an ad that has an appropriate deeplink including a language variable,
When I open the app for the first time,
Then the app should parse the language variable in the deeplink, automatically set the language, and show apps in the selected language.

Given that the deeplink doesn't contain a language variable or a language that doesn't exist,
When I open the app for the first time,
Then no language should be auto-selected and the user should be prompted to select a language from the Settings modal.

============
Notes:

This is a really solid tutorial about deeplinking:

https://www.kodeco.com/18330247-deep-links-in-android-getting-started

It includes how to test passing information into an install via ADB so we can test everything upfront before even running an ad!

**Comment by ashishkrr** [comment]
@burrage Hi ben Do we have any demo "ad" link or url just to test?
or if we don't have, do i need to create here firebase dynamic link ? if yes, please provide me firebase dynamic permission so i will create one dynamic link to test.

am done with the development and currently am able to navigate from url to app and parse the language, the URL for demo i used
https://www.curiouslearning.org/test?code=Hindi

this works only to navigate from URL to app but if app is not there then this will go to browser and it opens some page at the curiouslearning website. But we want to redirect to play store.

**Comment by Ashish1998** [comment]
Hiii @burrage @ashishkrr Can this feature be tested?

**Comment by burrage** [comment]
Yes, yes it can! 

I'll leave it to @ashishkrr to fill in more details on installing the app via adb and passing parameters to "simulate" that a deferred deeplink has been passed to the app.

Some good QA test cases here @Ashish1998, similar to the Acceptance Criteria above, would be:

1.) Passing a language that we know we have (English, French, or Hindi).
2.) Not passing language at all.
3.) Passing a language that we don't have or is total nonsense (Japanese, Klingon, or ABC123.language.BIZ).

**Comment by burrage** [comment]
And most importantly, I'll let @ashishkrr be the person that says when it is ready to test!

**Comment by Ashish1998** [comment]
Yeah sure @burrage.
