### ISSUE TITLE
FTM UX deep dive

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#368]
**User Story**
As a UX designer and QA engineer,
I want to make a comparison document between the Unity Feed The Monster and the web version for each scene and action,
So that we can have a document from which to 1.) make tasks cards that could bring the web version closer to the Unity version or 2.) have a record of a difference that we cannot replicate due to technical limitations or are consciously choosing not to replicate.

**Acceptance Criteria**
Given that I have two devices (physical or a virtual device through AVD), one with Unity FTM and one with FTM web,
When I play through each action or screen on the game in both versions, compare their behaviors, and note any differences in a Google Doc file,
Then I should have a document to discuss with the team and stakeholders on what differences should become task cards and what should be left as a difference.

======
Notes:
- Tinsley observed-- "The second thing I noticed was around when the music plays. Music's very captivating and energizing. And then the unity version the music plays whenever you're not on the normal gameplay screen with the agar monster on the hill. Which means during the selection of profiles or level selection or in between screens between levels. All those places are when the music plays. And we should mimic that in the PWA version."

**Comment by Ashish1998** [comment]
Hiii @burrage Here is the link of the document for comparison between FTM unity version and web version.
Please share your feed back on this, Thank you.
https://docs.google.com/document/d/1kT_K0Z9KCUmu62rmQz4BMeWeLXhK-1Fnm1Y0UsN9JWw/edit?usp=sharing

**Comment by burrage** [comment]
Very thorough @Ashish1998 ! Nice work. 

A question:

Since you have played the game A LOT on potentially a few different devices-- have you ever felt like the size of the monster would make it hard for a child with poor motor skills to drag the stone to it? Would making the monster larger be beneficial?

And a follow up question for one of the developers:

If we were to increase the size of the monster programmatically by a fixed percent-- what would the ramifications be vs if we were to resize all the assets instead? 

We'll most likely be returning to this document over a few rounds, but for now, I'm highlighting in yellow some issues that I'll be adding to the backlog that I think will improve the UX.

We can move this to Done for now though!

**Comment by Ashish1998** [comment]
@burrage The current size of the monster in web version will not be a problem for the kids to give input, but when i compared it with the unity version I observed that in unity version bigger monster was more attractive compared to the web app monster size.
