### ISSUE TITLE
'null' is present on the stones.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#370]
**Describe the bug**
In FTM Hindi version on some of the stones "null" is present.
List of levels:

- Level 11 puzzle 4
- Level 13 puzzle 1
- Level 14 puzzle 2 
- Level 14 puzzle 3

**To Reproduce**
1. Install the latest CR Container app which contains Hindi version and open it.
2. Play the above mentioned levels.

**Expected behavior**
Any letter should be present on the stones.

**Screenshots**

![Screenshot (270).png](https://images.zenhubusercontent.com/6423d12de632a60d8c53681e/282fb1f9-5875-4342-b177-24cffd5dcf56)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: MI Note 6 pro
 - OS: Android 9

**Additional context**

**Comment by burrage** [comment]
@weepingwitch On these levels/puzzles, can we check to make sure the JSON isn't malformed or perhaps has an unanticipated character? Thanks!
