### ISSUE TITLE
Target letter is not displayed on the thunder icon.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#371]
**Describe the bug**
Here in the FTM Hindi version the target letter is not displayed on the thunder icon, so it will be difficult for the user to give the input
Levels with the issue:

- Level 13 puzzle 1
- Level 14 puzzle 3

**To Reproduce**
1. Install the latest CR Container app which has FTM Hindi and open it.
2. Play the above mentioned levels.

**Expected behavior**
Any letter should be displayed on the thunder icon.

**Screenshots**

![Screenshot (271).png](https://images.zenhubusercontent.com/6423d12de632a60d8c53681e/155e4bdd-1437-4cf9-8010-f146857ec1eb)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser: Chrome
 
**Smartphone (please complete the following information):**
 - Device: MI Note 6 pro
 - OS: Android 9

**Additional context**

**Comment by burrage** [comment]
@weepingwitch On these levels/puzzles, can we check the JSON to make sure there is a target please?
