### ISSUE TITLE
Adjust FTM gameplay timing

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#383]
**User Story**
As a Product Owner,
I want to match FTM Unity's gameplay timing wherein the target letter will appear and be spoken and the app will wait 5-6 seconds before the letter stone options appear OR if the user taps anywhere on the screen after the target letter audio has been spoken,
So that we don't overwhelm the user with too much information by waiting for the target audio to finish playing before presenting choices, to allow the user to speed up the experience by tapping the screen to reveal the letter stones they could pick, and to move the game along by displaying the stones without user input if they are not paying attention.

**Acceptance Criteria**
Given that I am playing a FTM level,
When the puzzle loads,
Then I should see the target (if available) and the target audio should play.

Given that I am playing a FTM level puzzle, the puzzle has loaded, and the target audio is playing,
When the target audio finishes playing,
Then I should be able to tap the screen anywhere to reveal the answer stones.

Given that I am playing a FTM level puzzle, the puzzle has loaded, and the target audio is playing,
When the target audio finishes playing and the game receives no touch input from the player after 5-6 seconds,
Then the answer stones should appear automatically.

**Comment by Ashish1998** [comment]
https://drive.google.com/file/d/1VG05Y4NhHaAVV_3fqLLyn-yLjLX3oUrj/view?usp=share_link
