### ISSUE TITLE
loading the level takes more time.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#390]
**Description**

- The first time after caching the data when user clicks on the level it is taking around 10 seconds to load the level.

https://images.zenhubusercontent.com/518897719/2edd0b5f-e686-4901-ac75-9168d855ea41/screenrecorder_2023_05_03_17_03_41_913.mp4

- When user clicks on next button or replay button it takes 5 to 6 seconds to load the level.

https://images.zenhubusercontent.com/518897719/e4040837-981c-416b-8b92-8c8c626a3807/screenrecorder_2023_05_03_17_05_13_691.mp4

**Comment by divyahariharan2103** [comment]
Not reproducible any more. Hence closing the task
