### ISSUE TITLE
Arabic dev server build for local language expert QA

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#394]
**User Story**
As a Product Owner,
I want to build a right-to-left reading language (like Arabic) on the development server,
So that we can determine what issues we face, if any, in displaying content in different writing systems that reads right-to-left instead of left-to-right and we measure how much engineering capacity and total length of time it would take to make a FTM that might require more engineering and QA time.

Arabic JSON file: https://github.com/curiouslearning/ftm-asset-api/blob/main/fulljsons/AllARABIC.json

Audio files: https://github.com/curiouslearning/ftm-languagepacks/tree/master/ARABIC/sounds

**Comment by Ashish1998** [comment]
@amitsinghsutara Missing audios:
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ضِـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـذ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/حَــضَــنَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـغَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/جَــرَس.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/رَسَــمَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/خَــلَــطَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/صَــنَوْبَر.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـلَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـدَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/حَــسَــمَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/عَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/حِــكايات.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/صَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـظَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/مَــضَــغَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ثِــياب.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ثِـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/هِـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـلوك.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/خَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/يِـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـخور.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ﺺَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/يُــحافِــظُ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/كَــتَــبَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/بُرْتُــقال.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـثا.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ظَــهَــرَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/مَــرَح.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/سَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـمَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـنَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـهِد.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/سَــجَــدَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـزَر.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/مَــنَــحَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/طَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ئِـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/حَــبَــسَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/دَغْـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/حَــمَــدَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـرَس.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـزَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/حَــدائِق.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/لَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ظَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/قَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـذَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/دَغْــدَغَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/شَــراب.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/هَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/صُــخور.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/نَــوافِذ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/سَــمَر.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـكَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/رَكَــضَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/فَــراشات.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـشَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/جَــزَر.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـظُـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/فَــحَــصَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـر.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـعَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـدَع.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/غَــضِــبَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـسَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/هـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/مَــدَحَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/يَشْـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـدا.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـرا.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/رَكَــعَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/غَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـضَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـلو.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ﻭ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـحَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـهار.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/مُجْــتَــهِد.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ﻂَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/غِـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/قَــرَعَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـطَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـباح.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/زَحَــفَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ضِفْــدَع.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـفَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ﺑَـجَع.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـثَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـجَع.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/تَــثاءَبَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/سافَــرَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـحا.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/مَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/حَــرَثَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـلَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/سَــحاب.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/شَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـمَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/يَشْــرَبُ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/نُــباح.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـه.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/نَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـوا.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/يُـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـفَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـصَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـهَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/غُــيوم.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/كَــذَبَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/حَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـرَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/صُنْــدوق.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/نَــهار.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/سَــرَدَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/نُــعاس.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/سَــكَــبَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/طَــبَــعَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـحاب.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/حَــرَسَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـتَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـعاس.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـبَ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـتَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/مَخْــلوقات.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـشَـ.mp3
https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـضَ.mp3

**Comment by amitsinghsutara** [comment]
hey @burrage ,
Here's the updated list of audio missing in the ftm_arabic which we were not able to find in the github repo as well as in the master drive!
[https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/مَـ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%85%D9%8E%D9%80.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/سَـ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D8%B3%D9%8E%D9%80.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/حَـ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D8%AD%D9%8E%D9%80.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـحَـ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D8%AD%D9%8E%D9%80.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـمَـ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D9%85%D9%8E%D9%80.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـسَـ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D8%B3%D9%8E%D9%80.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـرَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D8%B1%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـدَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D8%AF%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـمَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D9%85%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـر.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D8%B1.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/سَــمَر.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D8%B3%D9%8E%D9%80%D9%80%D9%85%D9%8E%D8%B1.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/سَــرَدَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D8%B3%D9%8E%D9%80%D9%80%D8%B1%D9%8E%D8%AF%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/حَــسَــمَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D8%AD%D9%8E%D9%80%D9%80%D8%B3%D9%8E%D9%80%D9%80%D9%85%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/مَــرَح.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%85%D9%8E%D9%80%D9%80%D8%B1%D9%8E%D8%AD.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/مَــدَحَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%85%D9%8E%D9%80%D9%80%D8%AF%D9%8E%D8%AD%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/حَــرَسَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D8%AD%D9%8E%D9%80%D9%80%D8%B1%D9%8E%D8%B3%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/رَسَــمَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D8%B1%D9%8E%D8%B3%D9%8E%D9%80%D9%80%D9%85%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/حَــمَــدَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D8%AD%D9%8E%D9%80%D9%80%D9%85%D9%8E%D9%80%D9%80%D8%AF%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـكَـ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D9%83%D9%8E%D9%80.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـتَـ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D8%AA%D9%8E%D9%80.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـفَـ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D9%81%D9%8E%D9%80.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـتَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D8%AA%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـفَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D9%81%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـبَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D8%A8%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـحاب.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D8%AD%D8%A7%D8%A8.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ســـحـــرَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D8%B3%D9%80%D9%80%D9%80%D8%AD%D9%80%D9%80%D9%80%D8%B1%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/رَـــمَــــضَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D8%B1%D9%8E%D9%80%D9%80%D9%80%D9%85%D9%8E%D9%80%D9%80%D9%80%D9%80%D8%B6%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/سَـــفَــــرَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D8%B3%D9%8E%D9%80%D9%80%D9%80%D9%81%D9%8E%D9%80%D9%80%D9%80%D9%80%D8%B1%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـقَــدَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D9%82%D9%8E%D9%80%D9%80%D8%AF%D9%8E.mp3)
    [https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/ـفَـــهَــــرَ.mp3](https://feedthemonsterdev.curiouscontent.org/lang/arabic/audios/%D9%80%D9%81%D9%8E%D9%80%D9%80%D9%80%D9%87%D9%8E%D9%80%D9%80%D9%80%D9%80%D8%B1%D9%8E.mp3)

**Comment by amitsinghsutara** [comment]
We are also lagging the feedback audio's as well for ftm_arabic!
