### ISSUE TITLE
Brazilian Portuguese dev server build for local language expert QA

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#397]
**User Story**
As a Product Owner,
I want to try building Feed The Monster Brazilian Portuguese,
So that we can determine how much engineering capacity and total length of time it would take to complete 1 version of Feed The Monster in the new web format that's relatively straight-forward.

Brazilian Portuguese JSON file: https://github.com/curiouslearning/ftm-asset-api/blob/main/fulljsons/AllBRAZILIANPORTUGUESE.json

Audio files: https://github.com/curiouslearning/ftm-languagepacks/tree/master/BRAZILIANPORTUGUESE/sounds

**Comment by ashishkrr** [comment]
@burrage title, fantastic, great these png file i cannot be able to find in this link.

https://github.com/curiouslearning/ftm-languagepacks/tree/master/BRAZILIANPORTUGUESE/art/titles

please tell me where i can check for those files.
Thanks Ben

**Comment by burrage** [comment]
@ashishkrr We won't be using the PNG files for the feedback text anymore since it is a production hassle to make them instead of using text rendering instead... 

But we will still need the text itself... and it looks like it is in English currently and not Brazilian Portuguese in the JSON file!

Would you mind spinning up a new bug card with the labels "bug" and "content" for this? We'll want to make sure it is changed in the JSON.

Here's what the 3 pieces of text for the English equivalents of "fantastic, great, and amazing" will be:

1. Fantástico!
2. Uau!
3. Incrível!

**Comment by Rajesh1041** [comment]
@burrage So just to be clear, are we using text based rendering in every build including english, hindi and french one?

**Comment by burrage** [comment]
Yup! Render all feedback text in every language as text.

**Comment by burrage** [comment]
We can use the same font as the letter rendering in a larger size.

**Comment by ashishkrr** [comment]
@burrage Can you please let me know where is the title png image for this Brazilian Portuguese language

**Comment by burrage** [comment]
@ashishkrr We want to change this to text-based rendering instead of an image too.

The title for Brazilian Portuguese is:

Alimente o Monstro!

We can use the same font we use for letter rendering, make it larger for the title, and we can use one of the yellow gradient colors from the image-based title (#f5db24) and can re-assess if we want to do any other CSS styling to it.

The reason we're trying to move away from image-based rendering of text is it adds a whole other production process when we go to localize a language and adds kind of unnecessary file size.

**Comment by burrage** [comment]
@ashishkrr Can we post the link to play this dev version of Brazilian Portuguese when it is ready for the local language QA? Thank you!

**Comment by Ashish1998** [comment]
Missing audios:
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/qu.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/n.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/v.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/m.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/f.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/p.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/r.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/s.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/b.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/d.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/x.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/t.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/z.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/e.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/l.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/i.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/c.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/g.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/o.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/h.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/a.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/j.mp3
https://feedthemonsterdev.curiouscontent.org/lang/brazilianportuguese/audios/u.mp3
