### ISSUE TITLE
Dropdown is not displayed properly.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#441]
Here the options of the dropdown is displayed up
![Screenshot_2023-05-29-13-11-45-06_9654051c21660445b69bc848f64982aa.jpg](https://images.zenhubusercontent.com/6423d12de632a60d8c53681e/ea666a2c-ef42-40a5-882c-3502530740d5).

**Comment by burrage** [comment]
We can leave this in the Backlog for now as we will be re-designing the language selection process at some point.

**Comment by Ashish1998** [comment]
Sure @burrage

**Comment by burrage** [comment]
This may be handled in the UI redesign task (https://github.com/curiouslearning/FeedTheMonsterJS/issues/564). Closing as duplicate.
