### ISSUE TITLE
Level progress issue.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#466]
**Describe the bug**
Here the timer is moving very fast, and we are not able to give input properly then it automatically progress to further levels and directly lands us to result screen without doing any thing.

**To Reproduce**
1. Install the latest apk.
2. Download the English app content and open the app.
3. Click on play button and click on level 1.
4. Don't give any input and you will be able to see the issue.

**Expected behavior**
The level progress should work properly even if we don't give any input.

**Screen Record**

https://images.zenhubusercontent.com/518897719/70254d24-857b-4c17-aa16-8995bef7256d/record_2023_06_06_16_31_44.mp4

**Smartphone (please complete the following information):**
 - Device: MI note 6 pro
 - OS: Android 9

**Additional context**

**Comment by divyahariharan2103** [comment]
Hi @burrage We are not able to reproduce this issue other than @Ashish1998 device . Unable to reproduce on browser stack or android studio as well.
Can you please let me know if you are able to reproduce this issue ?

Thanks,
Divya

**Comment by burrage** [comment]
I have had this happen on v1.0.14 on a physical device as well. Unfortunately, there doesn't seem to be any particular circumstances when it occurs. Sometimes it happens, sometimes it doesn't.

I do think we need to figure out how we can bubble up errors from a physical device so we can better troubleshoot.
