### ISSUE TITLE
Auto-push generated JSON and language media files to development branch on GitHub

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#479]
**User Story**
As a developer,
I want to figure out how to auto-push a JSON file and a folder of language media files from Google Drive to the FTM-JS development branch on GitHub,
So that we can automate the process of deploying the necessary files to create a new or updated language version to our development server.

**Acceptance Criteria**
Given that I have a JSON language file and the associated media assets on Google Drive and a script to commit said files to the development branch of the FTM-JS repo,
When I run the script,
Then the language JSON and the media assets should be committed to the development branch, which in turn, will be deployed by CircleCI to the development server, and available to test in the development APK.

**Comment by divyahariharan2103** [comment]
Hi @burrage 
Can you let us know what "Auto push" means here?

**Comment by burrage** [comment]
Yes, so "auto-push" here means finding a programmatic, automated way to push (or commit) files from Google Drive to the development branch on GitHub. So assume that a language JSON file and all the media files exist on Google Drive. We need to determine if we can automate committing those assets to the development branch-- is it even possible? How would we do it? (e.g. we need a non-person GitHub account created with write permissions to the FTMJS repo where we programmatically pass that account's credentials and a commit command with the accumulated assets (the JSON and all audio files) from Google Drive.

For greater context of where this will be used, it's best to read through the [automation process document](https://docs.google.com/document/d/1FqJ4FKLpTJeqlSLqr_L1zDmZrm0kY3z2lboSu8hlXD4/edit?usp=sharing). This task specifically is 5b sub-bullet ii-- so it will run AFTER a bunch of script checks required to generate the JSON.

Ideally, if doing this is even possible, is that this automation should be able to dock into the [Google Cloud Function(s)](https://github.com/curiouslearning/FeedTheMonsterJS/issues/482) that starts the JSON generation process.

**Comment by burrage** [comment]
Also to be clear PLEASE do split this task up into two components:

1.) Research-- Can this be done? How? What components are needed to do this (e.g. programmatic GitHub user, script, connection to Google Drive, or even maybe there's even a third-party service that does this already)? (We'll have a conversation around does this fit into the Google Cloud Function(s) running as part of the JSON generation process).
2.) Execution-- build the script and test it.

We'll make a separate task for integrating this portion into the Google Cloud Function workflow.

**Comment by ashishkrr** [comment]
@burrage I tried with the credential which you sent, and i feel that is not good way to do, because in that process, i needed to authentication my system git environment with the credentials you sent, So we need to try with the personal access token way to authentication or  0Auth way.
please provide me personal access token first to try.
Thanks!

**Comment by burrage** [comment]
@ashishkrr Check your DMs on Slack!
