### ISSUE TITLE
Run missing asset report on 20+ languages

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#486]
**User Story**
As a developer and Product Owner,
I want to run the JSON check and missing audio scripts on 20 languages to write a report on what we find if we were to try to build each of these languages,
So that we can identify any further problems with being able to build these localizations.

**Acceptance Criteria**
Given that I have run the JSON check and missing audio scripts on 20 language JSON files and for 20 language packs from GitHub and have [recorded the results in the following Google Doc](https://docs.google.com/document/d/1n_WF_i6CunsxIr18G120ZURPlhwq4G0TlORf_WttGBs/edit?usp=sharing),
When I view the doc,
Then I can see what languages could be built without issue.

[Language JSON files](https://drive.google.com/drive/folders/1XwKKuBPLbHl93ba95XjEDzdqq8RgntYj?usp=drive_link)

Languages:

1. Zulu
2. Pashto
3. Luganda
4. Nepali
5. Ukrainian
6. Afrikaans
7. Amharic
8. Azerbaijani
9. Bangla
10. Australian English
11. Indian English
12. South African English
13. West African (Nigerian) English
14. Farsi
15. Georgian
16. Haitian Creole
17. Hausa
18. Igbo
19. isiXhosa
20. Javanese
==============
If we have time, remaining languages:

21. Kinyarwanda
22. Kiswahili
23. Kurdish
24. Malagasy
25. Malay
26. Marathi
27. Ndebele
28. Oromo
29. SePedi
30. Sesotho
31. Shona
32. Siswati
33. Somali
34. Spanish
35. Tagalog
36. Tajik
37. Thai
38. Tsonga
39. Tswana
40. Turkish
41. Twi
42. Urdu
43. Venda
44. Vietnamese
45. Wolof
46. Yoruba

**Comment by divyahariharan2103** [comment]
Hey @burrage ,

can you provide the JSON's for the above language so that the team can run the script.

Thanks,
Divya

**Comment by burrage** [comment]
@vinay961861 @Ashish1998 Just a heads up, we looked at Luganda, Afrikaans, and Australian English and found that the files should all be on the ftm_languagepacks repo. Do you know if the script checking for the media is case insensitive?

Is it also looking in multiple folders for the audio? Or just one? I know for our FTM web versions, we mentioned we would put ultimately like to put everything into a single /audios/ folder, but on the ftm_languagepacks repo, we have multiple directories like "/Words/", "/Letters/", etc.

**Comment by Ashish1998** [comment]
Hiii @burrage we noticed that the .wav extention  is in upper and lower case

**Comment by divyahariharan2103** [comment]
Hey @burrage 
Any update on this ?

**Comment by burrage** [comment]
Which language should we look at for examples @Ashish1998 @divyahariharan2103 ? It sounds like we would need to re-generate the JSON with an updated path if that's the case.

@weepingwitch See above messages for JSON path confusion in the audio assets. We had decided to forego the more specific subfolders and lump everything together in a root /audios/ folder to cutdown the onus on correctly filing each media asset-- with Stephanie, we determined there wouldn't be any overlap if we combined to one root folder.

**Comment by burrage** [comment]
Sorry, misunderstood what was written.

@weepingwitch , I see the JSONs have that agreed-upon path already .../[language]/audios/ so we are good there.

@Ashish1998 @divyahariharan2103 We'll need a task to physically consolidate the subfolders of the audio we've downloaded into this root level .../[language]/audios/ folder. Does it make sense to do this physical consolidation as part of another process we have already? Like when we are converting the files to MP3?

**Comment by Ashish1998** [comment]
Hiii @burrage we have updated the issue document. Please have a look into it.
Thank you.
