### ISSUE TITLE
Remaining 26 language checks

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#500]
**User Story**
As a developer and Product Owner,
I want to run the JSON check and missing audio scripts on the remaining 26 languages to write a report on what we find if we were to try to build each of these languages,
So that we can identify any further problems with being able to build these localizations.

**Acceptance Criteria**
Given that I have run the JSON check and missing audio scripts on 26 language JSON files and for 26 language packs from GitHub and have [recorded the results in the following Google Doc](https://docs.google.com/document/d/1n_WF_i6CunsxIr18G120ZURPlhwq4G0TlORf_WttGBs/edit#heading=h.w2oxl5eg6bz3),
When I view the doc,
Then I can see what languages could be built without issue.

[Language JSON files](https://drive.google.com/drive/folders/1XwKKuBPLbHl93ba95XjEDzdqq8RgntYj?usp=drive_link)

Languages:

21. Kinyarwanda
22. Kiswahili
23. Kurdish
24. Malagasy
25. Malay
26. Marathi
27. Ndebele
28. Oromo
29. SePedi
30. Sesotho
31. Shona
32. Siswati
33. Somali
34. Spanish
35. Tagalog
36. Tajik
37. Thai
38. Tsonga
39. Tswana
40. Turkish
41. Twi
42. Urdu -- REMOVED (Content issues)
43. Venda
44. Vietnamese
45. Wolof
46. Yoruba

**Comment by Ashish1998** [comment]
Hiii @burrage @weepingwitch I have completed checking all the languages and among this 
For following languages,
- Kiswahili (json is not present and folder is not present in ftm-langpacks).
- Malagasy (Json is not proper and folder is not present in ftm-langpacks).
- Urdu (json is not present and folder is not present in ftm-langpacks).
- Tswana (Json is not proper).

**Comment by burrage** [comment]
@Ashish1998 

2 of the missing JSON languages are under slightly different names:

1.) [Kiswahili = Swahili](https://drive.google.com/file/d/1gDrB-4xGWwm_G-PfjkhYQCJxVM8kRO21/view?usp=drive_link) 

2.) [Malagasy = Malagache](https://drive.google.com/file/d/1NiHjm-9HmivOZ7cbPC6XgCBIO_LwTkhT/view?usp=drive_link)

And we'll need to generate ones for Urdu and Tswana, @weepingwitch .

**Comment by Ashish1998** [comment]
Thank you @burrage.

**Comment by burrage** [comment]
Tswana needs to be rebuilt so may take a bit longer. We are going to remove Urdu from the list of languages as we have content problems with Urdu.

**Comment by Ashish1998** [comment]
Ohh ok @burrage
