### ISSUE TITLE
FTM languages batch #3 using automation processes

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#501]
**User Story**
As a developer and Product Owner,
I want to build 14/46 of the remaining Feed The Monsters using our [new automated process](https://docs.google.com/document/d/1FqJ4FKLpTJeqlSLqr_L1zDmZrm0kY3z2lboSu8hlXD4/edit?usp=sharing),
So that we can run through the automation process, determine how functional it is in its current state, and if we will be able to accomplish building and releasing all remaining 46 FTMs before the end of July.

**Acceptance Criteria**
Given that I have [all the JSON files](https://drive.google.com/drive/folders/1XwKKuBPLbHl93ba95XjEDzdqq8RgntYj?usp=drive_link),
When I run the automation scripts to check the JSON and audio on Google Drive, optimize the audio to .mp3, commit the content to the development branch, and update the development manifest to be able to select a newly built language,
Then I should be able to hand over 14/46 Feed The Monsters for local language QA.

Languages we decided to tackle for this batch:

- Bangla
- Farsi
- Georgian
- Haitian Creole
- Igbo
- Javanese
- Kinyarwanda
- Nepali
- sePedi
- SiSwati
- Tajik
- Ukrainian
- Vietnamese
- Wolof

**Comment by vinay961861** [comment]
Ukrainian
Nepali
Bangla
Farsi
Georgian
Haitian Creole
Igbo
Javanese
