### ISSUE TITLE
Android 13 targeting investigation + disable AAID at GMS level

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#504]
**User Story**
As a Product Owner,
I want to create a Curious Reader production build that targets Android 13 (API level 33) that disables Android Ad ID collection at the GMS level (see note from Google Play below for more),
So that we can QA test Curious Reader compatibility with Android 13 and fill out the additional compliance declarations on Google Play associated with Android 13 and have it checked for compliance by the Google Play Store.

From Google Play:

If your app is updated to target API level 33 (Android 13), ensure that your app or a library included in your app does not declare the new AAID permission, or that AAID is disabled. For more information on this permission and how to include or disable AAID, [see this article](https://support.google.com/googleplay/android-developer/answer/6048248). By updating to target API level 33 and not including the permission, AAID will automatically be disabled (set to a string of zeros).

**Acceptance Criteria**
Given that I have made a build of the Curious Reader container app that targets Android 13 (API level 33),
When I play it on a physical or virtual device that uses Android 13,
Then the app should behave as it did on previous versions of Android.

**Comment by divyahariharan2103** [comment]
@burrage As the current prod app is working as expected and also is approved by play store, please let us know if we still need to proceed with this task?

**Comment by burrage** [comment]
@divyahariharan2103 We can indeed move this to DONE! The 

<uses-permission android:name="com.google.android.gms.permission.AD_ID" tools:node="remove" />

line in the Android Manifest took care of the compliance stuff in conjunction with the new OS targeting :-)

Thankfully much easier than expected and less effort than we were anticipating with the 3! (hopefully!)

**Comment by divyahariharan2103** [comment]
ok thanks Ben !!
