### ISSUE TITLE
Dark mode issue

### ISSUE THREAD

**Issue by divyahariharan2103** [curiouslearning/FeedTheMonsterJS#514]

**Comment by burrage** [comment]
@Ashish1998 We will re-design this pretty soon, so grey is fine for now.

Just a heads up, though, the language selection area also shows white text in dark mode. So from this screenshot, we'd still have white text on a white background (which is unreadable) unless the grey background is used throughout the dropdown (both initial dropdown and for the language choices).

**Comment by amitsinghsutara** [comment]
Hey @burrage ,

Thank you for sharing your thoughts,
Please have a look at this screenshot once and share your thoughts as well!

Best Regards
Amit Kumar Singh

![image](https://github.com/curiouslearning/FeedTheMonsterJS/assets/102941445/333660db-9bca-4a0f-80d8-d8716393c030)
