### ISSUE TITLE
"Wrong answer" animation revision for all 4 phases of the Magnet Monster

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#518]
Updated "noEat" animation frames are in each phase folder.

[Magnet Monster animations](https://drive.google.com/drive/folders/1cA3GaykH3rkzRdpF5l3CBJHpbyKHgumm?usp=drive_link)

FYI, the Phase 4 animation has a slightly different naming convention. Do you think this is an issue?

**Comment by rakshith-arch** [comment]
@burrage its not a issue, as we are using these images only for creating the spritesheet, after creating the spritesheet we are naming it as per our requirement,

**Comment by amitsinghsutara** [comment]
Hey Team,
you can check the wrong answer animation on this url!
https://devcuriousreader.wpcomstaging.com/FeedTheMonsterJS2.3/

**Comment by burrage** [comment]
Geoff's comments for revision:


> I would make a couple other changes on the programming side:

1.) The whole thing seems stretched vertically. The proportions are off. The food spits out vertically, so that means it gets lost at the top very quickly. I think unstretching it should help with that.

2.) Maybe a brief pause after dropping the food before the noEat animation starts, a duration that still feels responsive but giving us a little moment to breathe before the animation starts. I think that should improve legibility, and might even mean you don't have to repeat it two more times.

**Comment by burrage** [comment]
Also so we don't have to open another task for the revisions, we can move this back to In Progress and bump up the story points accordingly so it encapsulates initial implementation + revision.

Thanks!

**Comment by amitsinghsutara** [comment]
Hey @burrage ,

Hope you are doing well,
Regarding this task we have done some changes programmatically that helps us render more frames according to the type of animations, along with that we have also updated the wrong animation with the images provided previously!

Here's the wordpress on which you can check the changes ,
Here i have removed the restrictions of some gameplay rules, Also after every levels new monster will come!

check out this link:- https://devcuriousreader.wpcomstaging.com/FeedTheMonsterJS2.3/
Note:
need to turn on cors policy
Also after every level the next phase of monster will appear

**Comment by burrage** [comment]
This looks a lot better than it did before @amitsinghsutara !

This seems to be as far as we're going to be able to take this animation without the animation engine for syncing everything up, so let's move this on to Review/QA -> Done and call it a success for now!

**Comment by amitsinghsutara** [comment]
Hey @burrage ,

Thanks a lot for the feedback 🙌

Are we good to go to add these changes on the development build and then production?

**Comment by burrage** [comment]
Yup! Throw these into development!

**Comment by amitsinghsutara** [comment]
Hey @burrage ,

These changes are live on the development build!

Best Regards 
Amit

**Comment by burrage** [comment]
In QA, let's ensure this doesn't throw off where someone can drag a stone.
