### ISSUE TITLE
New download UI overlay icon

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#562]
**User Story**
As a Product Designer,
I want to use a [new download overlay icon](https://drive.google.com/file/d/1gDQa5c4J3SSDSskekjBwRH2zSTbgJ7Ef/view?usp=drive_link) in the Curious Reader container app,
So that we can replace our original placeholder icon.

**Acceptance Criteria**
Given that I open the Curious Reader container app,
When I select a language that isn't cached already,
Then I should see the new download overlay icon on top of the grey scale Feed The Monster app icon.

**Comment by vinay961861** [comment]
Hi Ben, good morning. Please share feedback on the new download icon.
![Screenshot_20230801_125937 (1)](https://github.com/curiouslearning/FeedTheMonsterJS/assets/62736791/81d22ab7-127e-4bc8-be80-d14b483011cd)

**Comment by vinay961861** [comment]
@burrage It wont be any problem from programming end,Please share your feedback about this changes

![Screenshot_20230803_124856](https://github.com/curiouslearning/FeedTheMonsterJS/assets/62736791/85d2b242-d031-43ec-93f6-12e79d168613)
![Screenshot_20230803_124959](https://github.com/curiouslearning/FeedTheMonsterJS/assets/62736791/7c6d03cc-01af-4a2c-988a-2d76afd1eda8)

**Comment by vinay961861** [comment]
Sure @burrage will try to round the edges and let you know
Thank you!

**Comment by vinay961861** [comment]
Please take look @burrage 
![Screenshot_20230807_124610 (1)](https://github.com/curiouslearning/FeedTheMonsterJS/assets/62736791/c736d665-147c-43b8-a1bf-1c0878bbc0b5)
Thank you!
