### ISSUE TITLE
Black screen appears after tapping if answer letters do not appear

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#578]
From Turkish QA-- possible race condition?:

"Sometimes the answer letters does not come at all. If i somehow tap on the screen when this happens, a black screen appears. (Screenshot-3). And i cannot play the game without completely restarting it."

![Screenshot 2023-08-02 at 3.30.40 PM.png](https://images.zenhubusercontent.com/58c973a851aa2c3057788ef8/16bf499f-0286-4de7-860b-1f54c91da67a)

Additional info from the same report that may be helpful:

"Sometimes answer letters come too late. In some occasions i waited for 5-6  seconds for them to come. (Sometimes they don’t come at all. )"

**Comment by Ashish1998** [comment]
Hiii @burrage, this issue was not reproducible. I tried it in couple of devices and in low end device as well.

**Comment by burrage** [comment]
Great! We'll go ahead and close this out.
