### ISSUE TITLE
Feedback audio plays multiple times on word levels

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#579]
From Turkish QA:

"Sometimes celebration voiceover repeats twice or thrice after successfully answering the question. (This happens only in word levels, not in the letter levels)"

Desired behavior:

The spoken feedback audio phrase should only play once when completing the puzzle.

**Comment by divyahariharan2103** [comment]
hy @burrage any update on this , can we move it to Done?

**Comment by burrage** [comment]
Yep, closing this out. I tested on both Turkish AND Yoruba and only heard the spoken audio feedback phrase once.
