### ISSUE TITLE
Feed The Monster theme music continues to play when locking the phone

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#582]
Similar to a past issue, when the Feed The Monster theme music plays, if you lock the phone, the theme music continues to play.

See #596 (related).

**Comment by Ashish1998** [comment]
@amitsinghsutara This issue is happening still if the phone goes to sleep when the cloud animation is playing, the FTM audio does not stop until we clear the app from the background.
