### ISSUE TITLE
Tutorial hand showed up on level 20

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#583]
From Georgian QA:

![Screenshot 2023-08-02 at 3.52.22 PM.png](https://images.zenhubusercontent.com/58c973a851aa2c3057788ef8/c137b6d3-aa11-4b9a-b07e-a93ed9b56741)

I think this should be resolved by #567 but logging to make sure we test.

**Comment by divyahariharan2103** [comment]
Hi @burrage This happens only in dev branch because of the dev tool . Can we ignore this issue?

**Comment by burrage** [comment]
Absolutely! Good to know that this will happen on the dev branch though. Thanks!
