### ISSUE TITLE
For Dev builds, show JSON version 

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#639]
**User Story**
As a QA Manager,
I want to see what version of the JSON was being used when a local language QA person QA'd an app,
So that we can ascertain when changes have been made and if JSON issues were resolved in a subsequent QA.

(e.x. v1.0.16 / jv1.11) -- 'jv' standing for "JSON version".

**Acceptance Criteria**
Given that I have an APK that points to the development server,
When I launch FTM,
Then I should see the JSON version next to the app version.

**Comment by vinay961861** [comment]
Hey @burrage ,
  Regarding this task, there is an update in the production JSON. Instead of having 'minVersion' and 'majVersion', we had 'version', and we utilized that for this task.
Thank you!
