### ISSUE TITLE
Get familiarized with JSON generation scripts

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#672]
**User Story**
As a developer,
I want to get familiarized with the [JSON generation scripts](https://github.com/curiouslearning/ftmjs-automation/tree/main/json%20generation/google%20cloud%20functions) and [forthcoming documentation](https://docs.google.com/document/d/19K0y2f4JvJbF3hve1GN2h-5BnooDMy_L47LKIeqtkks/edit?usp=sharing),
So that I can add on to the code base or troubleshoot issues that may arise.

**Comment by divyahariharan2103** [comment]
@burrage Can you let us know the steps to run the scripts locally, it would be helpful to start with the familiarization

**Comment by burrage** [comment]
Will pass along the question to Willow :-)

**Comment by burrage** [comment]
We should have the documentation ready pretty soon but I know the answer to this should be included!

**Comment by rakshith-arch** [comment]
@burrage @weepingwitch, when i was trying to deploy the script i came across the GCP(Google Cloud Platform), can you please give access to GCP project(development).

**Comment by burrage** [comment]
Sorry! I forgot to do this before I left for vacation. I'll get this to you later today @rakshith-arch

**Comment by burrage** [comment]
@rakshith-arch All set! This is the prod project (FTM-AppBucket3). In Cloud Functions, you'll see a "hello-world" function (the prod JSON generation function). Make a new Cloud Function and you can call it "dev-" whatever you like to help differentiate dev and prod :-)
