### ISSUE TITLE
Launch "Igbo" language to production

### ISSUE THREAD

**Issue by divyahariharan2103** [curiouslearning/FeedTheMonsterJS#700]

**Comment by burrage** [comment]
One more rebuild and publish to dev needed-- @divyahariharan2103. Not sure if we wanted to re-assign Amit...?

**Comment by divyahariharan2103** [comment]
Hi @burrage Amit was busy with the launching the CR books to prod so I have assigned it to @Nikhil77sutara

**Comment by amitsinghsutara** [comment]
Hey @burrage ,
The production server was not updated with the latest fixes for Igbo alignment,
That's why it's not been pushed to production!
Tomorrow we can go ahead with the release.

**Comment by burrage** [comment]
Moving out of "Done"-- see Slack message about level 1 balloon UI text.

**Comment by divyahariharan2103** [comment]
@burrage can you confirm if this is working for you?
