### ISSUE TITLE
Launch "Malay" language to production

### ISSUE THREAD

**Issue by divyahariharan2103** [curiouslearning/FeedTheMonsterJS#702]

**Comment by burrage** [comment]
This had a piece of audio that needed to be updated (re-MP3'd and filename changed to i.mp3) that doesn't look like it was done:

[i_sound.wav](https://drive.google.com/file/d/1S43titiPtD61beSSZ5LCdOMcfx5u3tLl/view?usp=drive_link)

**Comment by burrage** [comment]
Additional missing audio. I found it already, placed it in the right Drive location, ran the content_verification script, and got the e-mail that this is ready for a rebuild @amitsinghsutara @Nikhil77sutara !

**Comment by Nikhil77sutara** [comment]
> Additional missing audio. I found it already, placed it in the right Drive location, ran the content_verification script, and got the e-mail that this is ready for a rebuild @amitsinghsutara @Nikhil77sutara !

Thanks @burrage ,
me and Amit are looking into it.
we  will update the build.

**Comment by burrage** [comment]
@divyahariharan2103 @Nikhil77sutara Malay is ready for production!

**Comment by divyahariharan2103** [comment]
@burrage Malay is launched to prod !! Assigning to you and keeping it in review . Please confirm I will move to done

**Comment by divyahariharan2103** [comment]
@burrage Malay is launched to prod !! Assigning to you and keeping it in review . Please confirm I will move to done

**Comment by burrage** [comment]
All good @divyahariharan2103-- we can move these straight to Done-- nothing I need to be involved with for review!

Would it be helpful if I start adding AC to these prod tasks? Up to this point, we've done most of the QA upfront with the dev versions, and I'm afraid I would be a massive bottleneck if I had to review every app going through multiple times myself.

All we need a developer to do for the launch to prod is to 1.) make sure once they add the new app to the prod manifest that they see the language in the language dropdown and the app icon in the prod Curious Reader app, 2.) that they can launch the app, and 3.) play through one level to make sure the audio made it over to the proper server? I think that's enough to consider  the task Done.

Anyway... happy to add those ACs to each story if we'd like it in writing for each language?

Thanks!

**Comment by divyahariharan2103** [comment]
Thanks @burrage yes that would be helpful
