### ISSUE TITLE
"Next level" button issue in end level screen. 

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#716]
Here when a user gets 1 star or zero stars then the next button will not be displayed but if the user clicks on the next button position then they will be taken to the next level puzzle.

**Steps to reproduce**
1. Install the latest container app, and select a language and download the content.
2. Open the app click on play button and select a level puzzle.
3. In the puzzle give all wrong answers and get zero or 1 star.
4. Then in the end level screen click beside the "replay level" button (click on the right side of the replay button).

**Screen Record**

https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/ce36d3b3-9e67-4912-9ca8-152048301bd7

**Comment by burrage** [comment]
Wild find, @Ashish1998 ! 😄 😆

**Comment by Ashish1998** [comment]
@burrage 😅😄

**Comment by divyahariharan2103** [comment]
Closing this issue as it is no more reproducible @burrage
