### ISSUE TITLE
Launch "Kurdish" language to production

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#738]
**Acceptance Criteria**
Given that the production server now has the files that were on development for Kurdish,
When I add the prod URL to the prod manifest and I select "Kurdish" as a language,
Then I should see the app icon for FTM.

Given that I see the app icon for FTM,
When I open the app and play through the first level in its entirety,
Then I should see text in Kurdish and hear Kurdish audio.

**Comment by burrage** [comment]
Can we try the Adobe Arabic font for this language?

First, we'll want to run the Kurdish levelgen characters through our font checker to see if any letters show up wrong. 

And have @Ashish1998 check that this character: هـ 

Shows up OK in level 33 in the balloon UI and on a stone?

Visual guidance of how that character was displayed incorrectly using the previous font:

![Screenshot 2023-11-13 at 2 23 27 PM](https://github.com/curiouslearning/FeedTheMonsterJS/assets/5167186/cb9eecd6-1c52-4dc2-91d9-bec7e36c7e89)




هـ

**Comment by burrage** [comment]
@Ashish1998 @Nikhil77sutara @divyahariharan2103 Hey all, in Slack, Divya had mentioned that was rebuilt and tested?

But the issue in level 33 mentioned above is still present.

Can we see if the font we've chosen for Kurdish can render that particular character please? Thank you.

**Comment by amitsinghsutara** [comment]
Hey @burrage ,
The issue has been resolved by changing the right to left to true  in the Kurdish json since Kurdish is right to left!

**Comment by burrage** [comment]
@amitsinghsutara Ack!!! It wasn't automatically in the JSON that it is a right-to-left language instead of left-to-right?!

**Comment by amitsinghsutara** [comment]
Yes @burrage ,
It was not there by default!

**Comment by burrage** [comment]
@amitsinghsutara I spun up #918 task for next Sprint that we should add in so it's automatically set each time we generate a new JSON.

**Comment by burrage** [comment]
This is good to go for moving from development to production, though!
