### ISSUE TITLE
Launch "Javanese" language to production

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#747]
**Acceptance Criteria**
Given that the production server now has the files that were on development for Javanese,
When I add the prod URL to the prod manifest and I select "Wong Jawa" as a language,
Then I should see the app icon for FTM.

Given that I see the app icon for FTM,
When I open the app and play through the first level in its entirety,
Then I should see text in Javanese and hear Javanese audio.

**Comment by Ashish1998** [comment]
@burrage This is ready for Local QA.

**Comment by burrage** [comment]
@divyahariharan2103 Also leaving this unassigned at the moment for anyone that has capacity to do the production launch :-)
