### ISSUE TITLE
Research on performance tools

### ISSUE THREAD

**Issue by divyahariharan2103** [curiouslearning/FeedTheMonsterJS#754]

**Comment by Ashish1998** [comment]
Hiii @burrage I researched about some tools for checking the performance and response time of the animations and found a tool in the browser itself, under chrome - inspect feature.
- In this tool we can record a session of the web application and we can get the result and based on the result we can check whether the response time of the animation is more or optimal.
- We can even test the performance in specific devices through USB debugging as well.
These screenshots below shows a brief idea about it. 



![Screenshot (287)](https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/09b3a07f-485a-4cce-9d93-ca4dd4603187)
![Screenshot (288)](https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/912e3b8a-b1f5-4b9e-b859-e21bc14ba2db)
![Screenshot (289)](https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/36e11d62-298a-443b-b869-7111ee143d60)
