### ISSUE TITLE
[levelgen checking script] Check for matching [ ]s

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#767]
**User Story**
As a developer,
I want to check that there are always matching sets of square brackets [ ] that serve to combine multiple characters into a single character and to highlight the cell in red if there is not a matching pair,
So that we do not have JSON generation issues.

**Acceptance Criteria**
Given that I have an [ bracket only (or ] bracket only),
When the check script runs,
Then the cell with unmatched square brackets should be highlighted in red.

Given that I have matching [ ]s,
When the check scripts runs,
Then the cell should be the normal color to show there is no issue.

**Comment by Ashish1998** [comment]
Here in some cases if there is a extra " [ " or " ( " in the cell then it is not highlighting in Red color.
In row 33 and 36.

![Screenshot (291)](https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/7693e2f1-ebc4-46f9-a9d9-4a851542d594)

**Comment by Nikhil77sutara** [comment]
This is because we are only checking for  this brackets "()" in matchfirst level only.
And for "[]" brackets I have updated the script in the testing sheet .
