### ISSUE TITLE
Launch "Spanish" language to production

### ISSUE THREAD

**Issue by divyahariharan2103** [curiouslearning/FeedTheMonsterJS#776]
**Acceptance Criteria**
Given that the production server now has the files that were on development for Kurdish,
When I add the prod URL to the prod manifest and I select "Spanish" as a language,
Then I should see the app icon for FTM.

Given that I see the app icon for FTM,
When I open the app and play through the first level in its entirety,
Then I should see text in Spanish and hear Spanish audio.

**Comment by burrage** [comment]
#902 should solve one of our last technical issues. We are also waiting on a resolution to #899.

**Comment by divyahariharan2103** [comment]
@burrage This is ready for Local QA

**Comment by burrage** [comment]
@divyahariharan2103 @Nikhil77sutara All good for a production launch!
