### ISSUE TITLE
Audio of the Book keeps on playing even when app is in background.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#788]
**Describe the bug**
The audio of the sentences keeps on playing even when app is in background and even when the device is in sleep mode.

**To Reproduce**
1. Install Curious reader app and navigate to any book in any language.
2. Click on the Book app icon and play the book.
3. Go to any page and keep the app in background or put your device to sleep mode.
4. The audio keeps on playing.

**Screen Record**

https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/ad2aa719-6c62-4de7-992b-82fb03ca4f0c

**Comment by dz4va** [comment]
@Ashish1998 Ready for testing on develop!

**Comment by Ashish1998** [comment]
Issues is fixed.
