### ISSUE TITLE
Some books are not opening in offline mode.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#791]
**Describe the bug**
Some of the books are not accessible in offline mode. It shows 404 error.

The list of the books are as follows:

1. Ukrainian
- Cicadas Song
- Colours

2. Lugandan
- Colours
- Hide and seek

**Comment by burrage** [comment]
@Ashish1998 -- @dz4va reports that we've pushed changes and this is ready for testing again. Fingers crossed and let us know what you find!

**Comment by Ashish1998** [comment]
Hiii @burrage 
If we play a book in online mode, only that book is opening in offline mode the other books in the same language as well as other language is not opening, it shows "web page not found".


https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/80f0b263-ebf7-48c5-8219-94f4188050a6

**Comment by Ashish1998** [comment]
Hiii @burrage  now i am not facing the issue i am able to play the books in offline.

**Comment by burrage** [comment]
Great catch @Ashish1998 ! 

@dz4va Is this something you would want @ashishkrr's help on digging into while you focus on getting the Assessment ready for test deployment in development?
