### ISSUE TITLE
Launch "Luganda" language to production

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#804]
**Acceptance Criteria**
Given that the production server now has the files that were on development for Luganda,
When I add the prod URL to the prod manifest and I select "Luganda" as a language,
Then I should see the app icon for FTM.

Given that I see the app icon for FTM,
When I open the app and play through the first level in its entirety,
Then I should see text in Lugandan and hear Lugandan audio.

**Comment by burrage** [comment]
@amitsinghsutara Changes were made to content. It has since passed the content_verification and is ready for a rebuild!

**Comment by burrage** [comment]
Waiting on feedback text resolution.

**Comment by burrage** [comment]
OK @Nikhil77sutara we are game on for rebuilding this language!

One thing we want to be aware of... In Slack, Amit told me we were using audio from Github because it wasn't available on Google Drive... Now the audio IS available on Google Drive.

We can tell the old audio from the new audio because the old audio sounds kinda robotic and the new audio is not robotic and a female voice.

Anywho... Let's rebuild it and then I think we pass it along to local language QA again...

Thanks!

**Comment by divyahariharan2103** [comment]
@burrage This is ready for local QA

**Comment by burrage** [comment]
On it!
