### ISSUE TITLE
Ability to check that a specific font can render all characters in a levelgen file

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#826]
**User Story**
As a developer,
I want to find a tool or service that allows me to provide the contents of a levelgen file, and a specific font, and be able to know whether that font would be able to render all the characters from that levelgen,
So that I can proactively, and retroactively, know if a font is able to render all the characters specified in a levelgen.

**Acceptance Criteria**
Given that I have a levelgen file and a font,
When I feed them into the checking process,
Then I should know whether the font is able to render all characters specified in the levelgen.

**Comment by amitsinghsutara** [comment]
Hey @burrage ,
We found this tool where we can test various fonts!
https://www.myfonts.com/products/bold-adobe-arabic-39327?queryId=f0da15251371b8004267a9eb3d4029e6&index=universal_search_data&objectIDs=5418490002

**Comment by burrage** [comment]
YESSS!!!!! Can we test that it is accurate to our experience? For instance, we know that Adobe Arabic Bold does NOT render the Ɔ and Ɛ correctly.

**Comment by burrage** [comment]
One other to add...

Google Fonts is also a solid resource for this... Check it out (and "Type Tester" tab)!:

https://fonts.google.com/noto/specimen/Noto+Sans?preview.text=Hello%20there%20%C6%90%20or%20%C6%86&preview.text_type=custom

I preloaded with some example Twi text we were having difficulty with so I've sent that font on to Stephanie for a look at it from the pedagogy standpoint.

**Comment by burrage** [comment]
@amitsinghsutara This looks good and exactly what we are looking for depending on the font used!

Have you tested the Adobe link with characters from a levelgen of a language we know DOESN'T display the characters for an Adobe font like Adobe Arabic Bold (e.g. Twi)? And characters from a levelgen of a language we know DOES display the characters?

 If so, that's all the testing we would need.
