### ISSUE TITLE
Launch "Australian English" language to production

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#832]
**Acceptance Criteria**
Given that the production server now has the files that were on development for Australian English,
When I add the prod URL to the prod manifest and I select "English - Australian" as a language,
Then I should see the app icon for FTM.

Given that I see the app icon for FTM,
When I open the app and play through the first level in its entirety,
Then I should see text in English and hear Australian English audio.

**Comment by burrage** [comment]
Content placed the audio in the wrong folder. Getting it to the right spot...

**Comment by burrage** [comment]
We should run the content checking script again on this language since we completed #899 .

**Comment by Nikhil77sutara** [comment]
Hy @burrage , In this language there is one missing audio . 
bit.mp3

**Comment by burrage** [comment]
@Nikhil77sutara Stephanie switched out the word in the levelgen to "pit" which we have :-) So we can run the check again and regen the JSON and we should be good to go!

**Comment by divyahariharan2103** [comment]
@burrage This is ready for Local QA to test
