### ISSUE TITLE
Launch "Indian English" language to production

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#833]
**Acceptance Criteria**
Given that the production server now has the files that were on development for Indian English,
When I add the prod URL to the prod manifest and I select "English - Indian" as a language,
Then I should see the app icon for FTM.

Given that I see the app icon for FTM,
When I open the app and play through the first level in its entirety,
Then I should see text in English and hear Indian English audio.

**Comment by burrage** [comment]
@Nikhil77sutara A heads up here-- running the content_verification against Indian English at the moment is showing up a lot of missing files that Stephanie says are in the correct Drive folder so this could be another piece of information related to #899 .

**Comment by divyahariharan2103** [comment]
@burrage This is ready for Local QA !!
