### ISSUE TITLE
Get familiarized with the Interactive Book environment and code

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#869]
**User Story**
As an Interactive Book environment developer,
I want to help onboard another developer resource to understand 

1. the environment, tools, and pieces in play for getting an interactive book to play on the web,
2. any existing codebases related to the interactive books and
3. the current problems and troubleshooting tactics we are employing in tracking down the problems related to integrating interactive books into the Curious Reader

So that we have an additional resource that can help in getting our first interactive book launched in production, we bring in other resources that have launched multiple languages of a sub-app, that we share knowledge and best practices across sub-apps, and we start moving toward a system where developers can easily move between different types of projects.

**Comment by ashishkrr** [comment]
hey @burrage  i went through the code, done with the setup, understood the flow of the code.
Most exploration i will do while doing any task on interactive book!
Thanks ben.
