### ISSUE TITLE
Higher reported crashes on devices 1.5 - 2 GB of RAM / ARM Cortex-A53 CPU

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#871]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUR4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f06fb1d7f528315fcfcad042993bbff21dc148d/Screenshot%202023-11-20%20at%203.45.42%20PM.png)

**Comment by Ashish1998** [comment]
We were unable to get any errors or warnings regarding this issue.
