### ISSUE TITLE
App crashes on startup for 1.5 - 2 GB of RAM / ARM Cortex-A53 CPU device

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#872]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTd4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--76fe5afb08bb966379b99faef0baeac3751762de/Screenshot%202023-11-20%20at%203.49.07%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekh4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed92e84d62be3a0e98f13c7678d11ca67ffbb75f/Screenshot%202023-11-20%20at%203.54.43%20PM.png)

**Comment by divyahariharan2103** [comment]
Similar to task #871 , hence closing this task
