### ISSUE TITLE
Implement Install Referrer for being able to report a conversion event back to Google Ads

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#877]
**User Story**
As a marketer,
I want the first time use of the Curious Reader container app to be linked to the marketing campaign that led to the user to find, install and use the app so that I have a way of passing conversion information back to Google Ads. This can be done via the [Install Referrer API](https://developer.android.com/google/play/installreferrer/igetinstallreferrerservice).

Via the Install Referrer API, setup a listener in the Curious Reader container app that reads the referrer data and then sends the data as an event to firebase.  Use the event name: "first_open_cl".  In this event send the campaign_id.  [Here is an example of how to read a referring Meta request](https://developers.facebook.com/docs/app-ads/install-referrer/).  If it comes from Meta, you will need to use the decryption key which is in a canvas attached to the slack channel curious-reader-and-web-development.  Needs to read both referrers from Meta and Google Ads

Done when:
- Install referrer implemented and proven to run on first open 
- first_open_cl event with campaign_id viewable in BigQuery via firebase
- Works for both Facebook and Google Ads 

Facebook URL to test: https://play.google.com/store/apps/details?id=org.curiouslearning.container&referrer=utm_source%3Dapps.facebook.com%26utm_campaign%3Dfb4a%26utm_content%3D%257B%2522app%2522%253A0%252C%2522t%2522%253A1702591609%252C%2522source%2522%253Anull%257D&fbclid=IwAR3wKHXbe61hYbAv87LhfMsFqYE_z4vfsHx2dZXpBtNyPiXuMVsfvJK75GY

(Note: This is from the "CR Tswana - South Africa" ad campaign so hopefully, when we decrypt what's in this string we should see something like that)
 
Google URL to test FIRST: https://play.google.com/store/apps/details?id=org.curiouslearning.container&referrer=utm_source%3Dcurious_learning_test

**Note about Google-- since Google Ads doesn't allow us to see what data would flow in the URL like Facebook does, we will need to run some real ads to see what data comes in as the definitive second test. Please let us know when we would want to start running those Google Ads to test in the comments!

Testing assistance details:
https://stackoverflow.com/questions/5890914/how-to-test-android-referral-tracking/6966718#6966718

**Comment by ashishkrr** [comment]
@burrage i have implemented as per android doc, to test it, i have used below URL for google ads
https://play.google.com/store/apps/details?id=org.curiouslearning.container&referrer=utm_source%3Dgoogle%26utm_medium%3Dcpc%26utm_term%3Dtest%26utm_content%3Ddemo%26utm_campaign%3Dtesting%26anid%3Dadmob

For this url,in android am getting referrer url as "utm_source=google-play&utm_medium=organic"
any idea what is expected ?

for Facebook ads, Can you try the below step in the facebook ad manager
![image](https://github.com/curiouslearning/FeedTheMonsterJS/assets/35664866/db4e5c5c-02b0-4de4-b510-0c269e0a2be4)

By doing these it says will get decrypted data automatically.

**Comment by burrage** [comment]
CC: @jeffoberlander to keep him in the loop.

@ashishkrr Hey hey!

On the Android end of things... Once we tap that link and install the app, we should expect everything after the `referrer=` portion from that URL. I believe it'll come as a single string that can be parsed into individual key-value pairs using the & as a delimiter like utm_source=google, utm_medium=cpc, utm_term=test, etc.

Please feel free to contact Willow on Slack too as we have done this before for the Unity version of FTM.

For the Facebook request-- those instructions are for an ad network and analytics platform called Adjust that we don't use.

**Comment by burrage** [comment]
New AAB sent to Play Store for review Jan 4th. Will need to test with links and Google Ad campaign to push more volume through when it is live.

**Comment by jeffoberlander** [comment]
I just ran the following query and it does not return any events:

SELECT *
FROM `ftm-b9d99.analytics_159643920.events_2024*`
WHERE
  event_name = 'first_open_cl'

**Comment by jeffoberlander** [comment]
I see a few events in there today.  All for organic search, no campaign data:

utm_source=google-play&utm_medium=organic

**Comment by jeffoberlander** [comment]
Hi Ashish.  I checked today and the referrer_url is coming in as "utm_source=(not%20set)&utm_medium=(not%20set)"

**Comment by burrage** [comment]
Some queries that can help to check--

Give me all first_open_cl events for the month of January for v2.6:

```
SELECT * 
FROM ftm-b9d99.analytics_159643920.events_202401* 
WHERE app_info.id = 'org.curiouslearning.container' AND app_info.version = '2.6' AND event_name = 'first_open_cl'
```

Give me just the unique referrer_url parameters over the last week for first_open_cl events:

```
SELECT DISTINCT(event_params.value.string_value)
FROM `ftm-b9d99.analytics_159643920.events_*`,
UNNEST (event_params) as event_params
WHERE
  _TABLE_SUFFIX BETWEEN FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 WEEK))
AND 
  FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)) 
AND app_info.id = 'org.curiouslearning.container' AND app_info.version = '2.6' AND event_name = 'first_open_cl' AND event_params.key = 'referrer_url'
```

**Comment by burrage** [comment]
@ashishkrr I made up a tutorial for the Marketing and Distribution team where we can try plugging in our own dynamic UTM parameters into an ad to see if, in fact, we just very explicitly needed to tell Facebook what to send!

If this works, everything else we've been finding might be a red herring and we're all set-- so fingers crossed!!!

**Comment by burrage** [comment]
Blocked by Facebook dropping the feature we wanted to use :-(

We're reaching out to our Ads Account Manager to see if we can get routed to the right spot.

**Comment by burrage** [comment]
Update from my Meta Support session... That feature has been taken away from App Promotion campaigns which is what helps us track downloads so... ... We might be stuck :-(

**Comment by burrage** [comment]
@ashishkrr Just an FYI update:

I have a meeting with a technical contact at Facebook to figure out how others do this on Wednesday the 27th. We're in a bit of a bind in that when we change the campaign objective from App Promotion to anything else... it automatically scans the URL, sees it is a Play Store link, and asks us to change the objective to App Promotion! So there appears to be no way for us to add our own UTM parameters (in the App Promotion, you select the app from the Play Store and we can't even hardcode UTM parameters that way!)

In the meantime... the install referrer is getting the referrer_url if we just hardcode our own parameters so... that's working at least?

**Comment by burrage** [comment]
To circle back on this task, we will want to finish #1125 first as it has just one parameter to parse for. This can be for additional parameters.

We will need to discuss how we store these parsed parameters though.

**Comment by burrage** [comment]
Splitting into #1156 and #1157
