### ISSUE TITLE
Production launch of Ukrainian assessment

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#890]
**User Story**
As a Product Owner,
I want to add the Ukrainian assessment to the production manifest,
So that learners can launch and play the Ukrainian Assessment in the production Curious Reader.

URL: https://assessment.curiouscontent.org/?data=ukrainian-lettersounds

Icon: https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjh2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5b96e0d6e02fd3d158ef5926e84a80882bcd5a87/assessment_icon_placeholder.png

**Acceptance Criteria**
Given that I have the Ukrainian Assessment URL and app icon,
When I update the production manifest and select "Ukrainian" as a language in the Curious Reader,
Then I should see the Ukrainian Assessment icon.

Given that I see the Ukrainian Assessment icon,
When I launch it,
Then I should be able to play a few questions and hear audio.

**Comment by dz4va** [comment]
Here's the prod URL for the Ukrainian Assessment: https://assessment.curiouscontent.org/?data=ukrainian-lettersounds
