### ISSUE TITLE
Issues in Hindi interactive books.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#894]
- [ ] In book "The Bee and the Elephant" text and image are overlapping in **page 10**.

![Screenshot_2023-11-28-11-05-06-442_org curiouslearning container](https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/91ee474b-d70b-49a1-a858-f1074abb0bd1)

- [ ]  In book "Colours" the credits page is not present at the end of the book.

**Smartphone (please complete the following information):**
 1. Device: Oneplus Nord 2t
     Screen size: 6.43 inch
2. Device: MI Note 6 pro 
    Screen size: 6.26 inch

**Comment by burrage** [comment]
@Ashish1998 I just sent that back to our book builder to complete-- I wouldn't have it hold us up from launching this book, though. So I'd say we can close this out if the first point is done!
