### ISSUE TITLE
Issue in Igbo language letter only level.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#901]
**Describe the bug**
In Igbo language if there is 2 characters in letteronly levels then the characters are overlapping on each other and are displayed twice. 
You can see this issue in levels - 2, 26, 30

**Screenshots**
![Screenshot_2023-12-01-13-08-56-434_org curiouslearning container](https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/7d80c8c6-32ad-48db-8288-349fa2a3c986)
![Screenshot_2023-12-01-13-08-27-582_org curiouslearning container](https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/f772e6bc-ace2-41fa-aea3-53da784c1a45)
![Screenshot_2023-12-01-13-07-34-028_org curiouslearning container](https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/436fbfba-763e-4abc-a605-f5a1f140aedb)

**Smartphone (please complete the following information):**
 - Device: MI Note 6 pro
 - OS: Android 9

**Comment by Nikhil77sutara** [comment]
> Jumping in to add a similar problem appeared in the local language QA for Spanish that we just got back.
> 
> I'm assuming this fix will solve for ALL languages?

Yes @burrage , this fix will solve and work for all languages.
