### ISSUE TITLE
Issues in Assessment app.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#906]
**Describe the bug**
In the assessment app the issues are as follows:

- [x]  The loading animation in portrait mode looks like zoomed out.
- [x] In the main screen the position of the sound button is not proper.
- [x] For 1 question we can give multiple answers, and that many stars will appear in the header.
- [x] Once we complete the assessment and exit the app, again if we open the app the play button is not clickable.
- [x] **In offline mode the assessment is not playable.**   

**Screen Record**

https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/b73409f9-ea83-459d-a093-55fadbe120fd

**Smartphone (please complete the following information):**
 - Device: MI Note 6 pro
 - OS: Android 9

**Comment by burrage** [comment]
The stars appearing in random spots is intentional so we can take that off the list.

**Comment by Ashish1998** [comment]
Ok Ben.

**Comment by divyahariharan2103** [comment]
Hi @dz4va Rakshith has fixed the above ticked issues and the last one is said to be fixed by you.
Kindly merge Rakshith's PR whenever possible we will have QA test it.

**Comment by dz4va** [comment]
Ready for testing

**Comment by Ashish1998** [comment]
Here the 3rd point, we are still able to give multiple answer in 1 question.


https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/54a2e06e-a4d7-49d1-a102-4cdf7b44a00e

**Comment by Ashish1998** [comment]
@burrage @dz4va Whenever we give an answer and move to the next question should the audio play automatically even before clicking on the sound button?
