### ISSUE TITLE
Update Colours Hindi .h5p file

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#909]
This has the credits page added at the end that was previously missing.

https://drive.google.com/file/d/1trfs5RnyI9PGsKlyMsErxWZY3H59skE9/view?usp=drive_link

Send files to both development and prod S3 server buckets.

**Comment by ashishkrr** [comment]
@burrage In content.json we don't have those meta data which will parse and renders the image at the end of slides, i have putted the images for now and we required to update the content.json file as well.

**Comment by burrage** [comment]
CC: @dz4va for extra insight into the process since he has done this many times before! 

@ashishkrr I'm not sure I'm completely following.

The link in the original comment is an updated .h5p file. When we unpack that .h5p file, does the content.json file NOT have the meta data we need to add the final credits page?

Let me know!

**Comment by ashishkrr** [comment]
@burrage As per my understanding, Yes content.json file NOT have the meta data we need to add the final credits page, i informed same to george, he is looking into it and verifying the same.

**Comment by Ashish1998** [comment]
This file is added in dev version, but needs to be added in Prod version.
