### ISSUE TITLE
Add data collection to CR Web Player

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#917]
**User Story**
As a Product Owner,
I want to add the Firebase SDK to the CR Web Player,
So that I can track standard usage events while learners use the interactive and non-interactive books within the Curious Reader.

See Slack for npm install instructions.

**Acceptance Criteria**
Given that I have installed the Firebase SDK via NPM,
When I go into Firebase for the "Interactive Books" project (under FTM-AppBucket3),
Then I should see events being logged when I filter to just events coming from "Interactive Books".

**Comment by burrage** [comment]
Sending back into the backlog as we want to re-examine our nestled Firebase-within-Firebase approach in the near future.

**Comment by ashishkrr** [comment]
@burrage Can you please let us know which events or data we have to collect?

**Comment by burrage** [comment]
No custom events just the normal [out-of-the-box events](https://support.google.com/analytics/answer/9234069?hl=en) so all we need to do is include the SDK, right?

**Comment by divyahariharan2103** [comment]
Hi @burrage Can you kindly provide the required permission for @Ashish1998 so that he can proceed with the testing

**Comment by Ashish1998** [comment]
Thanks @burrage
