### ISSUE TITLE
Add Kurdish to language JSONs that have the right-to-left flag set to true

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#918]
**User Story**
As a developer,
I want to change the JSON generation process to include Kurdish as a language that gets the right-to-left flag set to true,
So that each time a Kurdish JSON is generated it correctly reports that it is a right-to-left language.

@weepingwitch will have insight into where this is done currently for languages like Arabic, etc.

**Acceptance Criteria**
Given that I have changed that Kurdish should be tagged with a right-to-left true,
When I run the content checks on Kuridsh and look at the JSON file that is generated during the process,
Then I should see that the right-to-left flag is always set to true for Kurdish.

**Comment by amitsinghsutara** [comment]
Hey  @burrage @weepingwitch  ,
Hope you are doing well  ,
Regarding setting true flag for right to left languages such as Kurdish,
While looking for solutions I found out that earlier we have a key value pair in the level gen sheets I.e. right to left -true for Arabic languages but right now we didn’t have that!
Now while generating new json's for all four four right to left languages i.e. arabic, Farsi, Pashto, AND Kurdish we are geting right to left as false!
