### ISSUE TITLE
language-checking-automation edge cases

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#922]
The language-checking-automation script is continuing to pick up false negatives, and, in some cases reported below, is failing to report missing audio. See individual languages for observed occurrences:

**Arabic:**

We've run the script and received a list missing audios that include both feedback phrases (great1, amazing, fantastic) and Arabic letters.

I took the first Arabic "missing" character (لو) and searched within the "Letters" folder for it just via the Chrome search bar and couldn't find it so maybe it's just not there, right? Get this... when I search via Google Drive's search bar it shows up as being in the Arabic "Letters" folder (where we expected it to be) but Google is showing the file name as mp3.لو instead of لو.mp3.

**Tsonga:** 

Stephanie is reporting that all the audio is in the Google Drive for Tsonga but the report is always coming up with these as false negatives for missing:

great1.mp3
ana.mp3
khoma.mp3
x.mp3
kofi.mp3
tele.mp3
vumba.mp3
tona.mp3
tima.mp3
thola.mp3
y.mp3
v.mp3
dyana.mp3
gama.mp3
nenge.mp3
o.mp3
fantastic.mp3
lembe.mp3
kona.mp3
bana.mp3
siva.mp3
amazing.mp3
pende.mp3
njiya.mp3
huku.mp3
enge.mp3
poto.mp3
fana.mp3
zukwa.mp3
epe.mp3
embe.mp3
mepe.mp3
vula.mp3
xuva.mp3
u.mp3
ima.mp3
baka.mp3
sika.mp3
iba.mp3
nene.mp3
mapa.mp3
ina.mp3
tiya.mp3
xona.mp3
wona.mp3
voya.mp3
mete.mp3
khapu.mp3
manga.mp3
wexe.mp3
khola.mp3
r.mp3
tshova.mp3
kulu.mp3
yona.mp3
jeke.mp3
bazi.mp3
mama.mp3

Additionally, Stephanie reports the word "rona" in the levelgen does NOT have audio in the Google Drive but "rona" does not show up as missing in the report.

Sounds like maybe we aren't looking at the right location (maybe looking at older GitHub only for this language???)...?

**Australian English & Indian English:**

Running the content check for both of these languages is reporting false negatives still (the content is in the folder but is reported missing).

Indian English example missing report:
cub.mp3
k.mp3
cut.mp3
e.mp3
mop.mp3
sw.mp3
spike.mp3
grape.mp3
home.mp3
write.mp3
q.mp3
strobe.mp3
whine.mp3
p.mp3
spoke.mp3
ome.mp3
o.mp3
sp.mp3
pl.mp3
ot.mp3
d.mp3
wed.mp3
nap.mp3
ted.mp3
ide.mp3
ite.mp3
cr.mp3
cute.mp3
it.mp3
flute.mp3
tan.mp3
frame.mp3
ipe.mp3
sheep.mp3
wheel.mp3
st.mp3
eak.mp3
str.mp3
n.mp3
price.mp3
chide.mp3
ume.mp3
ue.mp3
i.mp3
ch.mp3
eep.mp3
eel.mp3
lip.mp3
ame.mp3
fin.mp3
blade.mp3
great1.mp3
pleat.mp3
den.mp3
swipe.mp3
ake.mp3
sh.mp3
get.mp3
pit.mp3
nut.mp3
wr.mp3
gl.mp3
tree.mp3
r.mp3
squ.mp3
cap.mp3
in.mp3
rode.mp3
t.mp3
amazing.mp3
ap.mp3
rut.mp3
squeak.mp3
oke.mp3
pan.mp3
v.mp3
ean.mp3
blue.mp3
ape.mp3
map.mp3
wheat.mp3
fox.mp3
og.mp3
a.mp3
fl.mp3
box.mp3
pr.mp3
sip.mp3
bl.mp3
wh.mp3
pat.mp3
j.mp3
ale.mp3
mat.mp3
ade.mp3
ip.mp3
z.mp3
jet.mp3
ute.mp3
m.mp3
tap.mp3
top.mp3
pane.mp3
use.mp3
bleak.mp3
cat.mp3
eet.mp3
ike.mp3
ox.mp3
w.mp3
qu.mp3
globe.mp3
hop.mp3
stale.mp3
ule.mp3
glue.mp3
obe.mp3
une.mp3
fr.mp3
fume.mp3
br.mp3
if.mp3
ice.mp3
c.mp3
sweet.mp3
b.mp3
plane.mp3
ine.mp3
g.mp3
an.mp3
eat.mp3
bug.mp3
y.mp3
pin.mp3
wet.mp3
x.mp3
pot.mp3
shr.mp3
pox.mp3
clean.mp3
tr.mp3
shine.mp3
brake.mp3
spine.mp3
ode.mp3
tug.mp3
zip.mp3
ee.mp3
op.mp3
f.mp3
ane.mp3
dog.mp3
strode.mp3
rug.mp3
ten.mp3
u.mp3
can.mp3
h.mp3
s.mp3
fantastic.mp3
l.mp3
net.mp3
crane.mp3
cl.mp3
gr.mp3

First word "cub" is in the Drive.

Australian English example report:

nut.mp3
eat.mp3
blue.mp3
sh.mp3
plane.mp3
br.mp3
bleak.mp3
ale.mp3
d.mp3
pot.mp3
ice.mp3
wed.mp3
z.mp3
f.mp3
ted.mp3
pan.mp3
st.mp3
k.mp3
frame.mp3
ide.mp3
nit.mp3
lip.mp3
v.mp3
mop.mp3
s.mp3
swipe.mp3
m.mp3
home.mp3
ee.mp3
great1.mp3
crane.mp3
map.mp3
write.mp3
glue.mp3
squ.mp3
shrine.mp3
wheat.mp3
zip.mp3
nap.mp3
ade.mp3
j.mp3
can.mp3
cr.mp3
bug.mp3
ape.mp3
fr.mp3
eap.mp3
ten.mp3
pleat.mp3
pin.mp3
rode.mp3
pl.mp3
b.mp3
blade.mp3
mat.mp3
sp.mp3
obe.mp3
cap.mp3
globe.mp3
tree.mp3
box.mp3
sweet.mp3
pox.mp3
ue.mp3
sip.mp3
wr.mp3
n.mp3
tan.mp3
cut.mp3
a.mp3
o.mp3
pat.mp3
ean.mp3
bl.mp3
pr.mp3
spoke.mp3
if.mp3
g.mp3
flute.mp3
rut.mp3
in.mp3
hop.mp3
top.mp3
sheep.mp3
ode.mp3
sw.mp3
jet.mp3
ake.mp3
amazing.mp3
cat.mp3
eet.mp3
den.mp3
eep.mp3
e.mp3
r.mp3
shr.mp3
qu.mp3
p.mp3
eel.mp3
ume.mp3
cute.mp3
op.mp3
og.mp3
ike.mp3
ip.mp3
tr.mp3
tug.mp3
str.mp3
chide.mp3
ane.mp3
ipe.mp3
fox.mp3
gl.mp3
tap.mp3
pit.mp3
ap.mp3
u.mp3
spine.mp3
dog.mp3
h.mp3
price.mp3
fume.mp3
ame.mp3
ite.mp3
spike.mp3
an.mp3
use.mp3
get.mp3
i.mp3
l.mp3
gr.mp3
strobe.mp3
ine.mp3
cl.mp3
t.mp3
it.mp3
x.mp3
bit.mp3
fl.mp3
pane.mp3
brake.mp3
squeak.mp3
ch.mp3
ome.mp3
wet.mp3
wheel.mp3
net.mp3
whine.mp3
ute.mp3
eak.mp3
oke.mp3
w.mp3
ot.mp3
cub.mp3
stale.mp3
ox.mp3
y.mp3
fin.mp3
rug.mp3
grape.mp3
une.mp3
ule.mp3
c.mp3
clean.mp3
wh.mp3
fantastic.mp3
strode.mp3

First word "nut" is in the Drive folder.

**Comment by amitsinghsutara** [comment]
Hey @burrage ,
Hope you are doing well ;)
Today we have updated the google cloud function with the latest fixes for above issues,
But still in tsonga due to different file/format or restrictions i am not able to compare some files in the word type!
With the latest updates we are able to successfully test the arabic language which was resolved by increasing the querry count and normalizing it with "NFKD" WHILE fetching the files from the drive,
For Various english versions previously the issue was due to difference in name in the levelgen and the languages folder on the drive which is now resolved!

Best Regards
Amit

**Comment by burrage** [comment]
Thanks for the update on all of these @amitsinghsutara !

For Tsonga, do you mean we are having trouble with the .m4a files (instead of .wav or .mp3)?

**Comment by amitsinghsutara** [comment]
Hey @burrage ,
That's not an issue related to m4a format ,
Actually Ben there are many hidden files which we are not able to see in the drive,
Using the service account we are able to list the files but having issues while comparing!

**Comment by burrage** [comment]
Can you describe the issue a little more please @amitsinghsutara ? Perhaps throw out an example? I'm not sure I'm understanding exactly what's happening in Tsonga other than seeing that we have audio files in multiple formats (not great), the report lists files that are "missing", but Stephanie is confirming that they are in the Drive. I'm also seeing that the filenames of the words are all starting with a capital letter... is that causing the comparison problems perhaps...? Do you know what the comparison problem we're running into is exactly? Let me know, we absolutely can ask Stephanie to start standardizing things more or, on our end, we can add in additional types of standardization (e.g. toLower() all filenames, etc.)

**Comment by amitsinghsutara** [comment]
hey @burrage ,
Sorry for the inconveniences earlier most probably due to google drive security related issues we were getting two files with the same name like this :-
              ```
                thola.m4a (1znybNn5g2cskY-lhTDQVp7g4ZPhBo-Zp)
              47 thola_.m4a (1zldPTzFPcTlIJIKqeQu9Ocqq_YXpZWqK)
```  
 Due to which we were having issues in the comparison operations,
 But now we have resolved the issues by modifying the filenames a bit more!
 
 Along with that we have added additional changes for punjabi as well!

**Comment by amitsinghsutara** [comment]
Also @burrage ,
We are having a couple of missing audios in Bangla which we were not able to find!
ঝিঁ.mp3
বা.mp
