### ISSUE TITLE
Not able to play Lugandan assessment after 1st question. 

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#925]
**Describe the bug**
Once we open the assessment app, it loads and then after answering the 1st question we will get the sound button but if we click on it the audio is not playing and even the options will not appear. Hence we cannot progress for further questions. 

**To Reproduce**
1. Install curious reader app and select lugandan language.
2. Select the assessment app and open it.
3. Start playing it, after answering the question this issue will happen.

**Screen Record**

https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/0b12aaeb-2120-4948-b851-a43bf0687440

**Smartphone (please complete the following information):**
 - Device: MI Note 6 pro
 - OS: Android 9

**Comment by dz4va** [comment]
@Ashish1998 Hey Ashish, could you please provide any logs if you have them? Thanks!

**Comment by Ashish1998** [comment]
@dz4va Hiii George here in this text file i have added the logs for the issue.

[Logs for lugandan assessment.txt](https://github.com/curiouslearning/FeedTheMonsterJS/files/13915402/Logs.for.lugandan.assessment.txt)

**Comment by dz4va** [comment]
@rakshith-arch Can we confirm to move this task card to Done, Rakshith? Thanks!

**Comment by rakshith-arch** [comment]
Hey @dz4va the issue still exist in dev server, when i play that locally its working fine, i am able to play the game, only in the dev server its not working.
