### ISSUE TITLE
Launch "Vietnamese" language to production

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#928]
**Acceptance Criteria**
Given that the production server now has the files that were on development for Vietnamese,
When I add the prod URL to the prod manifest and I select "tiếng việt" as a language,
Then I should see the app icon for FTM.

Given that I see the app icon for FTM,
When I open the app and play through the first level in its entirety,
Then I should see text in Vietnamese and hear Vietnamese audio.

**Comment by burrage** [comment]
@Nikhil77sutara Is this ready for a local language QA? If so, please do @ me in response and switch the assignee to just me-- thank you!

**Comment by Nikhil77sutara** [comment]
> @Nikhil77sutara Is this ready for a local language QA? If so, please do @ me in response and switch the assignee to just me-- thank you!

Hy @burrage Vietnamese is ready for local language QA.

**Comment by burrage** [comment]
@Nikhil77sutara Vietnamese QA is back!:

https://docs.google.com/document/d/1__6EzFX-BBRXM1VaOUpQRmE80lOCzt6H37s5theoPJc/edit?usp=sharing

Most are fixes Stephanie will be doing but two things:

1.) One thing out of this QA that's probably applicable to all FTMs that we might want to consider is the boundary of where the stones can display. It looks like stones that have multiple letters (e.x. "ngh") can sometimes extend very slightly past the edge of the screen on _some_ devices. Do we have an x, y boundary based on the device viewport already or something similar that we might nudge + X on the left hand side and - X on the right hand side just in case we have stones that end up with multiple letters? That's probably something we would want to do that would help all languages-- not just Vietnamese.

2.) Also from this QA, we'd probably want to look at the font choice for this language. I'm not sure why the "m" character here is looking as it does or why they're saying it looks like a different font entirely? What font is Vietnamese using now?

Anyway... Peruse the QA... let me know if any questions but those would be the 2 that I think we should tackle.

**Comment by burrage** [comment]
@Nikhil77sutara Stephanie has finished making the changes to the levelgen and added new audio so now we can officially make all the needed changes.

**Comment by divyahariharan2103** [comment]
@burrage This is ready for Local QA

**Comment by burrage** [comment]
@Nikhil77sutara I'm still seeing the same tech issues listed in the first QA that I highlighted in a comment two weeks ago-- any insights there?:

"m" character looks like a different font-- can you verify that we are using the same font for display across all letters? What font is Vietnamese using? Is it different than other fonts we have used in the past?
![Screenshot_2024-01-24-15-25-28-523_org curiouslearning containerdev](https://github.com/curiouslearning/FeedTheMonsterJS/assets/5167186/a6eadabf-8b49-47fa-b847-c6071f05334a)

Stones with 3 or more letters can get cut off because they go off the screen:
![Screenshot_2024-01-24-15-32-20-721_org curiouslearning containerdev](https://github.com/curiouslearning/FeedTheMonsterJS/assets/5167186/cc98185d-356b-4a6f-ae8e-2e67fee2fb02)

**Comment by burrage** [comment]
#966 spun up to address stones with multiple characters getting cut off.

Would still be good to hear about the font for Vietnamese... Still not sure why the "m" character looks different compared to other letters!

**Comment by Nikhil77sutara** [comment]
> #966 spun up to address stones with multiple characters getting cut off.
> 
> Would still be good to hear about the font for Vietnamese... Still not sure why the "m" character looks different compared to other letters!

Hy @burrage ,
So here in vietnamese ,I checked the font and found that we are using the same font (consolas) which we are using for other languages.

**Comment by Nikhil77sutara** [comment]
Yes @burrage ,
We are having a file i18-font-mapping.ts in which we are maintaining the font of all the languages.

**Comment by burrage** [comment]
Holy moley! It's like MOST of the languages 😮  I'm really surprised this hasn't come up before... I'm going to check another language to see if it looks similar. Thanks @Nikhil77sutara !

**Comment by burrage** [comment]
@divyahariharan2103 Also been a while since this has been in QA so I'm leaving this unassigned and anyone that wants to do a prod launch and has bandwidth can be assigned :-)
