### ISSUE TITLE
Assessment layout changes

### ISSUE THREAD

**Issue by dz4va** [curiouslearning/FeedTheMonsterJS#929]
The assessment app should closely follow the layout reference attached to this task card.

<img width="439" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd055QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22649603dbba49b7eb2d53852a1e2b589ac5eb03/Curious%20Reader%20Assessment%20App%20Sketch%202023-12-14.png" alt="Curious Reader Assessment App Sketch 2023-12-14.png" />

**Comment by rakshith-arch** [comment]
@burrage @divyahariharan2103 @dz4va @Rajesh1041  i am not able to makeout what this task is about, can you please explain. If this task is only to disable the scrolling then i have already created PR for that.

**Comment by burrage** [comment]
Hey @rakshith-arch !

@dz4va Can go into deeper details, but I believe it was to provide the high-fidelity mockup of the layout and to make sure the audio button remains at the bottom.

**Comment by dz4va** [comment]
@burrage @rakshith-arch Yeah, this task actually was for just the reference, we have already reverted the changes that were made against the reference layout, we could probably move this task to done already!

**Comment by rakshith-arch** [comment]
Yaa sure thanks @dz4va @burrage .
