### ISSUE TITLE
Answer button reveal animation

### ISSUE THREAD

**Issue by dz4va** [curiouslearning/FeedTheMonsterJS#931]
Answer buttons should be revealed one by one with a slight delay based on the animation reference attached to this task card. The animation file for the answer button is an SVG animation in a .json file format so a library (ex. **Lottie**) addition may be a requirement before moving forward.

## Acceptance Criteria
  - The answer buttons should be revealed one by one
  - The reveal should have a slight delay between each button
  - The animation reference attached to the task card should be used
  - The animation file for the answer button is in .json format
  - A library (ex. Lottie) may be required to handle the SVG animation
  - The reveal animation should be smooth and visually appealing

[Animation file on Google Drive](https://drive.google.com/file/d/1_zzgmCLlJ5VdywIcXYDILUqFBd33Krsz/view?usp=sharing)

![LetterButton](https://github.com/curiouslearning/assessment-survey-js/assets/5410669/e509e211-320f-4cb9-b628-730b0d23dffc)

**Comment by rakshith-arch** [comment]
@burrage @dz4va @Rajesh1041 @divyahariharan2103 
Here for this task, i don't think we can add any text or DOM element into the animation, if i try to add it also it is showing seperately. I also did a research on this, it basically says that no text or DOM element can be added into animation, incase if text has to be included in the animation then while generating the json itself we have to include it and generate json, which i think is not a proper way(Which results in having 'total no of animation in one language= Total no of unique choices  that we are using in one language').

**Comment by Ashish1998** [comment]
Here for the first option in every question the animation is not properly playing.

https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/5a42e8b3-f26b-4fdf-b37d-41fea037b469

**Comment by Ashish1998** [comment]
Still for random and alternate questions the animation will not play properly for the First option.
(You can observe the difference from the 4th question in the below video)

https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/1ec6d848-abe8-4492-8345-41053117c91e

**Comment by divyahariharan2103** [comment]
Hi @dz4va , Kindly merge the PR for this task and let us know.
