### ISSUE TITLE
Star reveal animation

### ISSUE THREAD

**Issue by dz4va** [curiouslearning/FeedTheMonsterJS#933]
Each individual star should have a reveal animation based on the reference GIF file attached to this task card. The animation file for the answer button is a GIF animation.

## Acceptance Criteria
  - The individual stars should have a reveal animation.
  - Each star should animate separately.
  - The animation should be based on the reference GIF file attached to the task card.

[Animation file on Google Drive](https://drive.google.com/file/d/1ar5pd54M2uxpUqt_Ltu5fD1lt4JaUd6H/view?usp=sharing)

![StarAnimation](https://github.com/curiouslearning/assessment-survey-js/assets/5410669/74ada7f0-1d4a-496e-accf-2b0fe604da6e)

**Comment by rakshith-arch** [comment]
@burrage After implementing the above animation, below are the outcomes
  1. The animation color should be little darker(As it is not visible as shown in the image)
 <img width="1032" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUErQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--785cabd0f11d5cd1892ae6dd8dbc305e055d9450/Screenshot%20%2811%29.png" alt="Screenshot (11).png" />

  2. GIF animation loop should run only once as we want that animation should be played only once.
  3. GIF should be generated in such a way that the final frame in the animation should be just a star(Not the extra drawing of the animation such as middle frame as shown below)
  <img width="766" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWMrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92fc8c540c4678365854090f6b2294ecc2d5779c/Screenshot%20%2812%29.png" alt="Screenshot (12).png" />

**Comment by burrage** [comment]
Tagging @dz4va for the above ^^. Can you connect with Geoff regarding what @rakshith-arch is requesting? Thank you!

**Comment by dz4va** [comment]
On it, @burrage !

**Comment by divyahariharan2103** [comment]
@dz4va Any update on this task ?

**Comment by divyahariharan2103** [comment]
Hi @dz4va , Can you kindly merge the PR for this task and let us know
