### ISSUE TITLE
level_number missing from level_completed events in FTM

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#936]
**Describe the bug**
From v1.0.20 onward, the level_number key-value pair is not reported in the level_completed Firebase event.

**To Reproduce**
1. In BigQuery, for day-based query of level_completed events:

SELECT *
FROM `ftm-b9d99.analytics_159643920.events_20231219`
WHERE event_name = 'level_completed'

OR (for scale-- all of December)
SELECT *
FROM `ftm-b9d99.analytics_159643920.events_202312*`,
UNNEST (event_params) as event_params
WHERE event_name = 'level_completed' AND event_params.key = 'level_number'

**Expected behavior**
A level_number key-value pair should be reported with each level_completed event.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by jeffoberlander** [comment]
I also noted that app_id is not coming into any of the events.  Might be a separate issue to work on, but just noting this for when you are in the code.

**Comment by jeffoberlander** [comment]
Thank you @ashishkrr !  Related question: Can there be a "level_completed" event that has a level_number of 0?  Right now in the DB there are several of these.  Wondering if its pre-bug fix.  Or if its legitimate.  After "first_open" what will be the first event written ?  Would it be a "puzzle_completed" event?

**Comment by jeffoberlander** [comment]
Actually.  I just checked the DB and we are still getting "level_completed" events with no level_number

**Comment by burrage** [comment]
@jeffoberlander Circling back to the app_info values not being present on level_completed, etc. events comment-- oooo! I know why that is and it may be a bigger item to solve!

So... There are two instances of Firebase collecting data here:

1.) At the [Curious Reader Android app](https://docs.google.com/document/d/1oq9xBMgV6aOgzfpVGk1ZufoBRhDNdMsIIIa83busluo/edit?usp=sharing) level.
2.) At the individual app level ([FTM](https://docs.google.com/document/d/1HJ8GG5w6gDqHrgs7YW0FRHhQAMYPVVrG7M81vokcjVY/edit?usp=sharing), interactive book, [assessment](https://docs.google.com/document/d/14sBk6x8EyDOKTptwO884OdvqQetSZWrxTd3YWFoY_Qo/edit?usp=sharing)).

When we collect data from FTM, since it is grabbing data at the more granular web-app level, technically, that Firebase instance (2) doesn't know that FTM is being played within an Android app so it wouldn't automatically have the app_info data inserted.

Whereas events that are at the Curious Reader Android app level DO have app_info filled out automatically because it knows it is an Android app.

This probably brings up the question, "Why have two instances of Firebase collecting data like this?" I think it just came after the fact-- FTM JS came first and had Firebase at that level and when the Curious Reader container app came, we didn't have a way to capture those higher level Android events (what app is someone launching? etc.) so we put Firebase into that too.

That may not be the right path moving forward but it did also allow flexibility of collecting usage of the apps on the web and not solely within the Curious Reader app like if we ever just had people that wanted to play FTM on a computer or iOS device.
