### ISSUE TITLE
Add Hindi assessment to Curious Reader development + QA

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#945]
**User Story**
As a Product Owner,
I want to add the Hindi assessment sub-app to the Curious Reader,
So that we can expand our content portfolio available in the Curious Reader app and start the QA process.

App icon:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjh2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5b96e0d6e02fd3d158ef5926e84a80882bcd5a87/assessment_icon_placeholder.png)

Trello card with media assets + worksheet:

https://trello.com/c/SWR8maIX/7-hindi-india

Needs: Dev URL (George to confirm link)

**Acceptance Criteria**
Given that we have uploaded the Hindi assessment to the development S3 server, obtained the development URL, and added the app icon and URL to the development manifest,
When I open the Curious Reader container app and select Hindi as my language,
Then I should see the app icon for the Hindi Assessment.

Given that the Assessment has been uploaded to the development server and the app icon for the Assessment is visible, 
When I open and test the Assessment for caching and content,
Then I should be able to play through the Assessment and play the Assessment in offline mode without issue (also look for UI/UX issues).

**Comment by rakshith-arch** [comment]
Hi @dz4va here in the above task when i try to access the audios it is getting encoded(http://localhost:8080/audio/hindi-lettersounds/%E0%A4%95%E0%A5%87.mp3), i tried to decode this using builtin method 'decodeURI()', still its not working.

**Comment by divyahariharan2103** [comment]
Hi @dz4va The PR is raised for this task , can you kindly merge it and let us know.

**Comment by Ashish1998** [comment]
Here after playing for few levels facing a blocker where if i click on the sound button the audio is not playing and the options are not appearing. 

**Logs**
[Logs for hindi assessment.txt](https://github.com/curiouslearning/FeedTheMonsterJS/files/14306996/Logs.for.hindi.assessment.txt)


https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/249bbb78-d18e-4453-a1e5-04a546a4275f

**Comment by divyahariharan2103** [comment]
@dz4va , Kindly merge the PR for this task and let us know.

**Comment by Ashish1998** [comment]
@burrage @dz4va In Hindi Assessment for some questions Audios are not playing.


https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/316ef81e-9d7f-4f27-ad4e-e584f9240d95

**Comment by burrage** [comment]
@Ashish1998 Dang... Do we have more info about why some audio isn't playing from the console perhaps? Is it because the audio isn't on the server? And if it's not on the server, is it because we maybe don't have the file?

Tagging @amitsinghsutara as a heads up because this _might_ be a great use case for his new audio checking script ;-)

**Comment by amitsinghsutara** [comment]
Hey @burrage ,

Thank you for tagging me 🙌,
We have successfully tested the assessment cloud function for hindi and are able to successfully test the function,

As per above issue of audios, me and Rakshith are able to figure out the issue,
Rakshith will create a pr to fix this issue!

Best Regards
Amit

**Comment by Ashish1998** [comment]
Audio issue is fixed in Hindi assessment.
