### ISSUE TITLE
After install, transfer user to the PWA instead of the browser version

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#96]
**User Story**
As a UX designer,
I want to send the user into the Feed The Monster PWA landing page with the play button AFTER I have installed Feed The Monster or on subsequent visits to the install page if the app is already installed,
So that the user is trained to 1.) open the PWA Feed The Monster from their device homescreen when they want to continue playing and 2.) not need to return to the install webpage anymore. Additionally, we do not incur additional data transfers for ourselves and the users playing the game live on the web beyond the data needed to install and render the install screen.

Additional information about install detection, session transfer, and transfer after installation can be found [here](https://web.dev/learn/pwa/detection/).

**Acceptance Criteria**
Given that I have not installed FTM as a PWA,
When I visit [devcuriousreader.wpstaging.com/FeedTheMonsterJS](https://devcuriousreader.wpcomstaging.com/FeedTheMonsterJS),
Then I should see the "Install" button on the landing page.

Given that I am on the install page,
When I press the "Install" button,
Then the app should give the user prompt that the app is being installed.

Given that the "Install" button has been pressed,
When the app has finished installing,
Then the user should be redirected inside the PWA to the main landing page with the play button visible.

Given that I have installed the app and launched the PWA,
When I press the "Play" button on the landing page of the PWA,
Then I should be taken to the level select screen.

Given that I have installed the app and I return to the web address of the install landing page,
When I view the page,
Then I should see the "Play" button that should redirect me to the main landing page of the PWA.

**Comment by Ashish1998** [comment]
@burrage In this task the acceptance criteria is almost fully meet, but the 1 criteria is that when the user finish the installation of PWA he has to click on the play button to redirect to PWA app from browser. 
Please share your feedback, Thank you.
