### ISSUE TITLE
Not able to download multiple assessment app in different languages.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/FeedTheMonsterJS#963]
**Describe the bug**
We download and play a assessment in a language and if we try to switch to other language and download the assessment it will not download, the assessment in the 2nd language cannot be downloaded and we cannot play in offline. 

**To Reproduce**
1. Download an assessment app in a language (Ex, select Lugandan)
2. Switch to other language which has assessment app and try downloading the app (Ex, select Ukrainian)
3. In Ukrainian we cannot download the assessment app and play it in offline.

**Expected behavior**
We should be able to download and play assessment app in multiple languages.

**Screen Record**

https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/d23c03fd-d06d-4d27-b0d0-93c85900a7ff

**Smartphone (please complete the following information):**
 - Device: MI Note 6 pro
 - OS: Android 9

**Additional context**

**Comment by divyahariharan2103** [comment]
Hi @dz4va as this issue is related caching / offline mode I have assigned it to you. Please let me know if any concerns

**Comment by Ashish1998** [comment]
Logs for the issue is attached below,
[Logs for 963 issue.txt](https://github.com/curiouslearning/FeedTheMonsterJS/files/14135891/Logs.for.963.issue.txt)

**Comment by Ashish1998** [comment]
This issue is Fixed.
