### ISSUE TITLE
Lost "matchSound" and "spellSound" level types in development and production

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#967]
When checking Thai in development, I noticed "matchSound" and "spellSound" levels in the levelgen show the letters in the UI bubble above the monster when it should be only the play button (they're only supposed to hear the audio without the visual cue above the monster in these level types).

I went and checked a production language, Afrikaans, that has "matchSound" and "spellSound" levels and noticed those are showing the letter in the balloon above the monster too...

Did we lose the ability to render these level types? Is the JSON getting overwritten in a way we don't want? ...?

**Comment by Ashish1998** [comment]
UI issue - Here we are getting 2 play buttons in spell sound level types.

![Screenshot_2024-02-02-17-59-48-45_9654051c21660445b69bc848f64982aa](https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/a96704ca-eab4-4330-8be0-ccfaaf546434)

**Comment by Ashish1998** [comment]
Issue is fixed this level type is proper.
