### ISSUE TITLE
Audit Assessment Firebase events

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#968]
Spec: https://docs.google.com/document/d/14sBk6x8EyDOKTptwO884OdvqQetSZWrxTd3YWFoY_Qo/edit?usp=sharing

Here're those queries you can use--

Give me all data from the production data from Ukrainian one week back from yesterday:

```
SELECT *
FROM `ftm-b9d99.analytics_159643920.events_*`,
UNNEST (event_params) as event_params
WHERE
_TABLE_SUFFIX BETWEEN FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 WEEK))
AND
 FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))
AND
event_params.value.string_value LIKE 'https://assessment.curiouscontent.org/?data=ukrainian-lettersounds%'
LIMIT 1000
```

Same but filtered to the initialized event:

```
SELECT * 
FROM `ftm-b9d99.analytics_159643920.events_*`,
UNNEST (event_params) as event_params
WHERE   
_TABLE_SUFFIX BETWEEN FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 WEEK))
AND 
  FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))
AND
 event_name = 'initialized' AND event_params.value.string_value LIKE 'https://assessment.curiouscontent.org/?data=ukrainian-lettersounds%'
LIMIT 1000
```

To Do: Make Google Doc of items that don't match up to the data collection spec.

**Comment by rakshith-arch** [comment]
@burrage i have extracted the data in the [link](https://docs.google.com/spreadsheets/d/1Bj4umAn92UfxU9iVCvJ4o5HAun9kThg0IpJotX7Nj2A/edit#gid=714334423) here.

**Comment by burrage** [comment]
@rakshith-arch Don't worry about this task card now as @dz4va will take it from here.

Thank you both!
