### ISSUE TITLE
Audit FTM JS events in comparison to spec

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#972]
**User Story**
As a developer and Product Owner,
I want to create a Google Doc that compares this FTM JS [spec doc](https://docs.google.com/document/d/1HJ8GG5w6gDqHrgs7YW0FRHhQAMYPVVrG7M81vokcjVY/edit?usp=sharing) with event data being collected in Firebase,
So that we have a list of items where the data collected in Firebase may not match the specification.

TIP:

Use WHERE clause:

```
device.web_info.hostname = 'feedthemonster.curiouscontent.org'
```

To filter just to production FTM data and continue to filter with AND clause based on event_name.

**Acceptance Criteria**
Given that I have BigQuery access,
When I run queries on each event name and see what's collected via Firebase,
Then I should be able to note any differences in comparison to the spec.

**Comment by ashishkrr** [comment]
@burrage 
here is the doc file where i compared DATA TO REPORT and DATA IS REPORTING

https://docs.google.com/document/d/1RZVgc4BZoxuUzA-6WOm2mmbt9-MFTX-39cnvnA6z3hc/edit

**Comment by ashishkrr** [comment]
@burrage i have given the permission 👍

**Comment by burrage** [comment]
We're going to mark this as "Done" for now. We are going to take a look at standardizing data collection across all of our types of apps and what we have learned during this investigation process with this task and others is going to help inform how we should do that.
