### ISSUE TITLE
Audit Curious Reader Firebase events in comparison to the spec

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#973]
**User Story**
As a developer and Product Owner,
I want to create a Google Doc that compares this Curious Reader [spec doc](https://docs.google.com/document/d/1oq9xBMgV6aOgzfpVGk1ZufoBRhDNdMsIIIa83busluo/edit?usp=sharing) with event data being collected in Firebase,
So that we have a list of items where the data collected in Firebase may not match the specification.

TIP:

Use WHERE clause:

```
app_info.id = 'org.curiouslearning.container'
```

To filter just to production CR data and continue to filter with AND clause based on event_name.

**Acceptance Criteria**
Given that I have BigQuery access,
When I run queries on each event name and see what's collected via Firebase,
Then I should be able to note any differences in comparison to the spec in a Google Doc.

**Comment by amitsinghsutara** [comment]
hey @burrage ,
Hope you are  doing well ;)
Here's the document link for above mentioned curious reader firebase events as compared to  spec doc ([doc link](https://docs.google.com/document/d/1Ld84iPxdm5RzqXQ8zVjDakPqqhhZ5UoBd1b0i1xnaAc/edit)

**Comment by burrage** [comment]
@amitsinghsutara Doing well Amit! Thanks for sending this along.

A quick clarification, in the specification, it is also requesting that all non-custom events (read: Firebase standard events like session_start, user_engagement, screenview, etc.) also include these values:

- cr_language
- app_info.version
- manifest_version_number
- profile_number
- cr_user_id

Do those events have that information? I'm just seeing the app_launch custom event we made.

Thanks!

**Comment by amitsinghsutara** [comment]
Hi @burrage ,

Thank you for reaching out,

To address your question, I would like to confirm whether the additional values you mentioned, such as cr_language, app_info.version, manifest_version_number, profile_number, and cr_user_id, should be included with all non-custom events, in addition to the custom app_launch event!

**Comment by amitsinghsutara** [comment]
Hey @burrage ,

Another update :- 
Thank you for clarifying the details in the sprint review meeting,

Ben you were correct,
unfortunately currently we are not sending any data such as cr_language, app_info.version, manifest_version_number, profile_number, and cr_user_id which were mentioned by you previously in the firebase standard Events!

Best Regards
Amit

**Comment by burrage** [comment]
No prob!

And yeah, to repeat from Sprint Review, having these items (like the language and cr_user_id) across all events helps us easily filter our data or track the pathway a learner is taking through the app and ties their unique ID across the different experiences (FTM, interactive books, or assessment).

**Comment by burrage** [comment]
We're going to mark this as "Done" for now. We are going to take a look at standardizing data collection across all of our types of apps and what we have learned during this investigation process with this task and others is going to help inform how we should do that.
