### ISSUE TITLE
Port the audio checking script from FTM to the Assessment

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#977]
**User Story**
As a Product Owner, Assessment Developer, and a Content Manager,
I want to create a script that checks Google Drive for audio files in either .wav, .mp3, or .m4a formats that are listed in a "Letters" tab on Google Sheet ([example](https://docs.google.com/spreadsheets/d/1rzGn3_UiAHLPD4v2nLtuGhLPITWkAQRlRORMTL4z-QI/edit#gid=747952227)) and sends back a report through e-mail of what files are missing or says the Assessment is ready to build if there are no missing files,
So that we can determine whether we have all the letter sound audio that is needed to build an Assessment in a language.

PLEASE do suggest changes if necessary to the Assessment worksheet that need to be made to make it a more similar UX as how we do this for FTM (e.g. we need a link in a Google Sheet cell that says, "Run Web Content Check" or a metadata tab that contains the feedback phrase that we would like to use, etc.)

**Acceptance Criteria**
Given that I have an Assessment worksheet,
When I run the web content checking script,
Then I should receive an e-mail report of what audio files are missing (if any) or a message that there are no missing audio files and the Assessment is ready to build.

**Comment by amitsinghsutara** [comment]
Hey @burrage ,
hope you are doing well,
Regarding the audios for assessment we require the drive folder where we can access the audios for  assessment and check them!

**Comment by amitsinghsutara** [comment]
Hey @burrage ,

Hope you are doing well,
Just a reminder message for above comment;-
Need Drive Folder where we can have audios for all the assessments!

Best Regards
Amit

**Comment by burrage** [comment]
Hey @amitsinghsutara! I was traveling back from South Africa the past few days so I was unable to respond until today. 

Here's what we're looking at for Assessment audio at the moment--

[Assessment on the new team Drive](https://drive.google.com/drive/folders/16mfArt7NQds_jTYPYAp_Hp7thkQ3SD8v?usp=drive_link)

Note that the bulk of the audio to check is under Assessment -> Localizations -> [Language Name] -> [Unknown amounts of subfolders with different names] :-\

And the feedback audio appears to be under Assessment -> Assessment Media -> Assessment Audio -> Feedback Audio -> [Language Name]

Can we work with this or might we start asking Content to start standardizing folders (e.g. all production audio including the feedback phrase lives under Assessment -> Localizations -> [Language Name] -> Production Audio)?

**Comment by amitsinghsutara** [comment]
Thanks @burrage 🙌,
Let me have a look into it and will update you soon!

**Comment by amitsinghsutara** [comment]
Hey @burrage ,

Hope you are doing well ;)
Re;- Drive Access and example sheet can we provide the  access to the service account i.e. Data Exploration!

I tried Accessing the sheet and drive link provided earlier but i was unable to access the content of the drive and also i was not able to access the sheet as well using the service account!

Best Regards 
Amit

**Comment by amitsinghsutara** [comment]
Hey @burrage ,

Hope you are doing well ;)
Re;- Drive Access and example sheet can we provide the  access to the service account i.e. Data Exploration!

I tried Accessing the sheet and drive link provided earlier but i was unable to access the content of the drive and also i was not able to access the sheet as well using the service account!

Best Regards 
Amit

**Comment by burrage** [comment]
Hey @amitsinghsutara ! I think this should be all set. I just added you for access to the example sheet and I checked the "automaton" permissions on those folders and they appear to be set up the same way we did this for the FTM scripts.

Please let me know if you run into anything, though!

**Comment by amitsinghsutara** [comment]
Thanks @burrage ,

For your kind help like always 🙌,
Now I am able to completely access the content and all good to go with this task card,
Now only thing that is left to is create new cloud function!

**Comment by amitsinghsutara** [comment]
Status Update:-

Currently we have a working google cloud function which gets the character's from the google spreadsheet shared earlier and then check for their audio content in the google drive mentioned earlier,

Here's the google cloud function for hindi [cloud function](https://us-central1-ftm-b9d99.cloudfunctions.net/assessment_content_check/?sheet_id=1rzGn3_UiAHLPD4v2nLtuGhLPITWkAQRlRORMTL4z-QI&&lang=hindi)

For other languages assessment we will be needing more such google spreadsheets,
We got few more google spreadsheets on which we will be testing this cloud function and also edit the spreadsheets if necessary!

Best Regards
Amit

**Comment by Ashish1998** [comment]
- In Nepali version the audio for a character is showing as missing even if it is present the the drive folder.
![Screenshot (308)](https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/e5e6388b-95c1-4bc4-92c7-ffa86be19702)
![Screenshot (307)](https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/d4381454-2ed8-4fcb-9c2e-c3ef77823815)

- For Pashto the missing audio files list has a different extension like ".m4a"

![Screenshot (309)](https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/d2803161-03fe-498c-b487-1503cdb63422)
![Screenshot (310)](https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/86ff90fa-379c-4bc1-a952-c6c19fd81d18)

**Comment by burrage** [comment]
Hey Amit! 

Yup here's Ukrainian: https://docs.google.com/spreadsheets/d/1Jc8xwkcfwr2crqOg3JkDkYPR937hv38t1mewm63IRQs/edit#gid=698584351

Lugandan: https://docs.google.com/spreadsheets/d/1-fZu7If2HcI9I3uR2Lo3WSlqx2awZWl9dmX9g6H00FM/edit#gid=747952227

Nepali: https://docs.google.com/spreadsheets/d/1zsVM0qZjPC9kPSeWyv9uG0NGaPSSkJiXjcQvCToQpQY/edit#gid=315004542

Pashto: https://docs.google.com/spreadsheets/d/1X6PGZTwx4oP_XRkPts4zW261zK6z9JMC4nNlwLHIdWc/edit#gid=0

**Comment by amitsinghsutara** [comment]
Thanks @burrage 🙌

**Comment by divyahariharan2103** [comment]
Re-opening this issue to test Lugandan language
