### ISSUE TITLE
Upload new interactive Wolof books to development S3, deploy to dev Curious Reader, + QA

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#994]
**User Story**
As a Product Owner,
I want to upload the files needed to play Colours, Hide and Seek, Let's Fly, The Bee and the Elephant, and The Lost Doll to the development server, create development URLs for the stories, and launch them into the development Curious Reader,
So that we can do a quick QA speedrun if those books could be released to production.

[Wolof H5P files
](https://drive.google.com/drive/folders/1LQBojZ5eb6Q3PdMCjnkSV8bnZDmywf6k?usp=sharing)

[App icons](https://github.com/curiouslearning/FeedTheMonsterJS/issues/662) (if needed-- they're the same as all the other language icons)

**Acceptance Criteria**
Given that I have the Wolof H5P files for the stories,
When I've unpacked those and uploaded the necessary files to the development S3 bucket,
Then I should be able to create development server URLs that can be used to play the books in the development Curious Reader

Given that I have development server URLs to access the books,
When I add the URLs and app icons to the manifest file,
Then I should be able to read the stories in Wolof

Given that I can read the stories in Wolof on the development Curious Reader app,
When I QA the stories,
Then I should note if there are any issues in the Wolof stories as a new task card(s)

**Comment by divyahariharan2103** [comment]
Hi @dz4va , Can you please merge the PR for this task.

**Comment by dz4va** [comment]
Merged!
