### ISSUE TITLE
[Assessment] Disable Click interaction on answer buttons when animating

### ISSUE THREAD

**Issue by dz4va** [curiouslearning/FeedTheMonsterJS#997]
Users shouldn't be able to interact with the answer buttons that are slowly appearing on the screen after clicking the audio button and hearing the sound.

Acceptance Criteria
- When I as a user click any answer button during the answer button  sequential reveal animation shouldn't be able to register my input

**Comment by divyahariharan2103** [comment]
Hi @dz4va kindly merge the PR for this task

**Comment by Ashish1998** [comment]
Here still when the buttons are animating, if we click on the 3rd option it will take it as an input even before the 4th option is displayed.

https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/88876eac-99cb-4526-9cbe-55858944de7e

**Comment by dz4va** [comment]
@Nikhil77sutara Merged! Thank you, will be testing it myself today!
