### ISSUE TITLE
[Assessment] Speed up answer button sequential appearing animation

### ISSUE THREAD

**Issue by dz4va** [curiouslearning/FeedTheMonsterJS#998]
The answer button sequential reveal animation should happen faster, all four of them should appear in under a second or 2 (to be tested again).

Acceptance Criteria
- When I as a user click the audio button and hear the audio I should see the answer buttons appearing faster than the current speed.

**Comment by Ashish1998** [comment]
Hiii @dz4va this is the speed of the animation in one of the android 9 device. This feels good i guess.

https://github.com/curiouslearning/FeedTheMonsterJS/assets/99384703/b4fd2f74-360a-42c0-9f02-593eb079b60d
