### ISSUE TITLE
Create engineering task cards for identifying critical areas of FTM that would benefit from automated QA

### ISSUE THREAD

**Issue by burrage** [curiouslearning/FeedTheMonsterJS#999]
**User Story**
As a developer and Product Owner,
I want to create a list of engineering task cards that identify critical functional areas to the Feed The Monster game, and understanding how a learner is doing in their learning journey, that may benefit from automated QA testing,
So that as we continue making adjustments, improvements, and additions to the application, we make sure that the app and associated pieces like data collection, etc. behave as it should and can alert us if something changes.

**Acceptance Criteria**
Given that I have examined the app and associated components to making the app,
When I have identified critical operational and functional pieces that we want to monitor,
Then I should spin up task cards related to each test we would want to write so that they can be completed in a future sprint.

**Comment by Ashish1998** [comment]
Hiii @burrage here i have created a spreadsheet and have added some of the Critical functionalities which needs to be checked. Please do review the document and share your valuable feedback on this. Please let me know if any changes are required.
Thank you.
https://docs.google.com/spreadsheets/d/1iOcf_VMMQUoEMLJx4rcjpoRNOI_zBlwMOtD0o0DXjp0/edit#gid=0

**Comment by burrage** [comment]
@Ashish1998 That the data reports, with the structure and values that we would expect, is a big one we're missing!

**Comment by Nikhil77sutara** [comment]
Hey @burrage  ,
Hope you are doing well ;
Today we have updated the above shared [sheet](https://docs.google.com/spreadsheets/d/1iOcf_VMMQUoEMLJx4rcjpoRNOI_zBlwMOtD0o0DXjp0/edit#gid=0) with data reports along with that we also included the expected value  type and the value type which we are sending,
Here Ben, we have taken the expected value type from the examples share in the ftmpwa event [doc](https://docs.google.com/document/d/1HJ8GG5w6gDqHrgs7YW0FRHhQAMYPVVrG7M81vokcjVY/edit) but there we were not able to find the json_version number that is why we have kept that field empty!

**Comment by burrage** [comment]
This is awesome info to have @Nikhil77sutara (both from a documentation standpoint AND for use in our testing cases)!

So the json_version_number will be a combination of the "majorversion" and "minorversion" values in the languages JSON file. For example:

https://github.com/curiouslearning/FeedTheMonsterJS/blob/main/lang/afrikaans/ftm_afrikaans.json

Would be 3.4 for this example. 

And for what it is actually stored as...

Picking a random event in BigQuery... looks like a double!

![Screenshot 2024-03-26 at 11 59 10 AM](https://github.com/curiouslearning/FeedTheMonsterJS/assets/5167186/ff37a59a-8e36-4489-899d-49e5398588c5)

Hope that helps!

**Comment by divyahariharan2103** [comment]
Hi @burrage I have created all the automation tasks under the Epic: https://app.zenhub.com/workspaces/ftmpwa-62e36a7f4dbf3b0013e32e03/issues/gh/curiouslearning/feedthemonsterjs/1062

Here is the link of all tasks:

- https://app.zenhub.com/workspaces/ftmpwa-62e36a7f4dbf3b0013e32e03/issues/gh/curiouslearning/feedthemonsterjs/1064
- https://app.zenhub.com/workspaces/ftmpwa-62e36a7f4dbf3b0013e32e03/issues/gh/curiouslearning/feedthemonsterjs/1065
- https://app.zenhub.com/workspaces/ftmpwa-62e36a7f4dbf3b0013e32e03/issues/gh/curiouslearning/feedthemonsterjs/1066
- https://app.zenhub.com/workspaces/ftmpwa-62e36a7f4dbf3b0013e32e03/issues/gh/curiouslearning/feedthemonsterjs/1067
- https://app.zenhub.com/workspaces/ftmpwa-62e36a7f4dbf3b0013e32e03/issues/gh/curiouslearning/feedthemonsterjs/1068
- https://app.zenhub.com/workspaces/ftmpwa-62e36a7f4dbf3b0013e32e03/issues/gh/curiouslearning/feedthemonsterjs/1069
- https://app.zenhub.com/workspaces/ftmpwa-62e36a7f4dbf3b0013e32e03/issues/gh/curiouslearning/feedthemonsterjs/1072
- https://app.zenhub.com/workspaces/ftmpwa-62e36a7f4dbf3b0013e32e03/issues/gh/curiouslearning/feedthemonsterjs/1073
- https://app.zenhub.com/workspaces/ftmpwa-62e36a7f4dbf3b0013e32e03/issues/gh/curiouslearning/feedthemonsterjs/1074
- https://app.zenhub.com/workspaces/ftmpwa-62e36a7f4dbf3b0013e32e03/issues/gh/curiouslearning/feedthemonsterjs/1075
- https://app.zenhub.com/workspaces/ftmpwa-62e36a7f4dbf3b0013e32e03/issues/gh/curiouslearning/feedthemonsterjs/1076
- https://app.zenhub.com/workspaces/ftmpwa-62e36a7f4dbf3b0013e32e03/issues/gh/curiouslearning/feedthemonsterjs/1077

**Comment by burrage** [comment]
Excellent! Let's move this one to Done!
